## generated by RPythonic 0.4.8h	| host: 64bits
## http://code.google.com/p/rpythonic/
import os, sys, ctypes, inspect
__os = os
__sys = sys
__inspect = inspect
_CTYPES_CDLLS = []	# support loading functions from multiple libraries


PYTHON_RESERVED_KEYWORDS = 'for while in as global with try except lambda return raise if else elif eval exec and not or break continue finally print yield del def class assert from is pass'.split()


IS32BIT = (ctypes.sizeof(ctypes.c_void_p)==4)

_ISPYTHON2 = sys.version_info[0] == 2
if _ISPYTHON2:
	_NULLBYTE = '\0'
	_basestring = basestring
else:
	_NULLBYTE = bytes( chr(0), 'ascii' )
	_basestring = str

def _CHARP2STRING( charp, encoding='utf-8' ):
	b = bytes()
	i = 0
	while True:
		char = charp[ i ]
		if char == _NULLBYTE: break
		else:
			b += char
			i += 1
	return b.decode( encoding )

## try to load precompiled c-libraries from this directory, if the library is not there try to load from the system.
_clibs_dir = os.path.dirname(os.path.abspath(__file__))

def _load_ctypes_lib( name ):
	if name.startswith('/'):		# if a full path is given bypass all the loading logic and try to load it
		if __os.path.isfile( name ): return ctypes.CDLL( name )
	elif __os.name == 'posix':
		if __sys.platform.startswith('linux'):
			if not name.endswith('.so'): name += '.so'
			if not name.startswith('lib'): name = 'lib' + name

			if IS32BIT: 	path = __os.path.join(_clibs_dir,'linux32')
			else: 		path = __os.path.join(_clibs_dir,'linux64')
			url = __os.path.join( path, name )
			if __os.path.isfile( url ): return ctypes.CDLL(url)
			elif __os.path.isfile( '/usr/local/lib/%s'%name ): return ctypes.CDLL('/usr/local/lib/%s'%name)
			elif __os.path.isfile( '/usr/local/lib64/%s'%name ) and not IS32BIT: return ctypes.CDLL('/usr/local/lib64/%s'%name)
			elif __os.path.isfile( '/usr/lib/%s'%name ): return ctypes.CDLL('/usr/lib/%s'%name)
			elif __os.path.isfile( './%s'%name ): return ctypes.CDLL('./%s'%name)
			
			elif __os.path.isfile( '/usr/lib/%s.0'%name ):	# Fedora style
				return ctypes.CDLL('/usr/lib/%s.0'%name )
			elif __os.path.isfile( '/usr/lib64/%s.0'%name ):	# Fedora style
				return ctypes.CDLL('/usr/lib64/%s.0'%name )

			else:	# fallback
				print('[ falling back to loading from current process ]')
				try: return ctypes.CDLL(name)
				except: return ctypes.CDLL('')

		elif sys.platform == 'darwin':
			name += '.dylib'
			if IS32BIT: 	path = os.path.join(_clibs_dir,'osx32')
			else: 		path = os.path.join(_clibs_dir,'osx64')
			url = os.path.join( path, name )
			if os.path.isfile( url ): return ctypes.CDLL(url)
			else: return ctypes.CDLL(name) #fallback

	elif os.name == 'nt':
		name += '.dll'
		if IS32BIT: 	path = os.path.join(_clibs_dir,'win32')
		else: 		path = os.path.join(_clibs_dir,'win64')
		url = os.path.join( path, name )
		if os.path.isfile( url ): return ctypes.CDLL(url)
		else: return ctypes.CDLL(name) #fallback

RPYTHONIC_WRAPPER_FUNCTIONS = {}
RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES = []
RPYTHONIC_AUTOPREFIX_IGNORE = []

## ctypes does not clearly expose these types ##
PyCFuncPtrType = type(ctypes.CFUNCTYPE(ctypes.c_void_p))
PyCArrayType = type( ctypes.c_int * 2 )
PyCPointerType = type( ctypes.POINTER(ctypes.c_int) )
PyCStructType = type( ctypes.Structure )
CArgObject = type( ctypes.byref(ctypes.c_int()) )

class _rpythonic_meta_(object):
	'''
	Reserved Attributes:
		POINTER
		CSTRUCT
		CAST
	'''
	_rpythonic_ = True		# workaround for now, must have a way to know if object is a meta from another module, isinstance(o,_rpythonic_meta_) will fail in those cases. another workaround could be check sys.modules for other rpythonic modules and fetch _rpythonic_meta_ from there.
	def __init__(self, *args, **kw ):							# cheap trick, abuse **kw, and look for "pointer", "cast"
		if kw and 'pointer' not in kw: raise SyntaxError	# sorry, you can not init with keywords
		elif kw and 'pointer' in kw:
			if 'cast' in kw and kw['cast']:
				self.POINTER = ctypes.cast( kw['pointer'], ctypes.POINTER(self.CSTRUCT) )
			else: self.POINTER = kw['pointer']
		else: self.POINTER = ctypes.pointer( self.CSTRUCT(*args) )
		self.POINTER.pyobject = self	# .pyobject is local to this pointer "object"

	def __getattr__(self,name):
		if hasattr( self.POINTER.contents, name ):
			return getattr( self.POINTER.contents, name )

		else:	# when rpythonic failed to generate good bindings - these lookups should be cached
			for parent in self._rpythonic_parent_classes_:
				if hasattr( parent, name ):
					method = getattr( parent, name )	# should check if it really is an unbound method
					if method in parent._rpythonic_unbound_lookup_:
						func = parent._rpythonic_unbound_lookup_[ method ]
						n = func.name
						if len(func.argnames) > 1:
							argnames = func.argnames[ 1 : ]
							a = ',' + '=None,'.join( argnames ) + '=None'
							b = ','.join( argnames )
						else: a = b = ''
						lamb = eval( 'lambda self %s: %s( self.POINTER, %s )' %(a,n,b) )
						setattr( self.__class__, name, lamb )
						#return lamb	# this would return the unbound lambda, must call getattr again
						return getattr( self, name )
					else:
						# this can happen if self also inherits from the same parent class,
						# assume that by continuing this reaches that shared parent class,
						# and the lambda above is created as normal.
						continue
			## last resort, load from global name space ##
			G = globals()
			if name in G: return lambda *args: G[name](self.POINTER, *args)
			else:
				for prefix in self._autoprefix_:
					n = prefix + name
					if n in G: return lambda *args: G[n](self.POINTER, *args)
				print( 'possible auto-prefixes available', self._autoprefix_ )
				raise AttributeError

	def __call__(self, type=False):
		print('calling object is DEPRECATED - use ob.POINTER or ob.CSTRUCT')
		if type: return self.CSTRUCT
		else: return self.POINTER


def _rpythonic_generate_subclass_( name, struct, functions ):
	head = 'class %s( _rpythonic_meta_ ):' %name
	body = [ 
		'_rpythonic_parent_classes_ = []' ,
		'_rpythonic_unbound_lookup_ = {}' 
	]

	names = [ func.name for func in functions ]

	possibles = {}
	rank = []		# rank by longest name
	if len(names) > 3000: print('too many functions to use this hack')
	else:
		for n1 in names:
			prefix = ''
			for i,char in enumerate(n1):
				prefix += char
				if prefix not in possibles:
					possibles[ prefix ] = 0
					for n2 in names:
						if n2.startswith( prefix ):
							possibles[ prefix ] += 1

					if not rank or len(prefix) > len(rank[-1]) and possibles[prefix] > len(names)/4:
						rank.append( prefix )

	top = []
	while rank:
		best = rank.pop()
		if possibles[best] > len(functions)/2 and best not in names:
			if best.endswith('_set_') or best.endswith('_get_'): best = best[ : -4 ]
			elif best.endswith('Set') or best.endswith('Get'): best = best[ : -3 ]

			rem = []
			for other in rank:
				if best.startswith(other): rem.append( other )
			for r in rem: rank.remove( r )

			if best not in top: top.append( best )

		if len(top) > 3: break

	for n in names:		# find shortest prefixes #
		prefix = ''
		for i,char in enumerate(n):		# cammelCase
			if i==0: prefix += char; continue
			if char.isupper() and len(prefix) >= 2: break
			prefix += char
		if prefix and prefix != n and len(prefix) >= 2:
			hits = 0
			for other in names:
				if other.startswith( prefix ): hits += 1
			if hits >= 2 and prefix not in top:
				top.append( prefix )
				if len(top) >= 6: break

	## setup full names
	for func in functions:
		n = func.name
		if len(func.argnames) > 1:
			argnames = func.argnames[ 1 : ]
			a = ',' + '=None,'.join( argnames ) + '=None'
			b = ','.join( argnames )
		else: a = b = ''

		fhead = 'def %s( self %s ):' %(n,a)
		fbody = ['return %s(self.POINTER, %s)' %(func.name,b)]
		g = fhead + '\n\t\t' + '\n\t\t'.join( fbody )
		body.append( g )
		#body.append( '%s._rpythonic_function_ = %s' %(func.name, func.name) )

	## setup short names ##
	for n in names:
		for prefix in top:
			if n.startswith(prefix) and n[len(prefix):] not in names:
				alt = n[ len(prefix) : ]
				if alt and alt != n and alt not in PYTHON_RESERVED_KEYWORDS and not alt.isdigit() and not alt[0].isdigit():
					body.append( '%s = %s' %(alt,n) )
					names.append( alt )

	gen = head + '\n\t' + '\n\t'.join( body )
	try: exec( gen )
	except:
		print( gen )
		raise SyntaxError

	klass = locals()[name]
	klass.CSTRUCT = struct	# ctypes struct class

	klass._autoprefix_ = top
	for func in functions:
		unbound = getattr( klass, func.name )
		klass._rpythonic_unbound_lookup_[ unbound ] = func
		# klass.longname is klass.shortname = False
		# klass.longname == klass.shortname = True
	return klass

def _rpythonic_convert_structs_to_objects():
	G = globals()
	for klass in _OOAPI_:
		altname = name = klass.__name__
		prefix = ''
		for i,char in enumerate(name):
			if i==0: prefix += char; continue
			if char.isupper(): break
			prefix += char
		if prefix and prefix != name:
			hits = 0
			for other in _OOAPI_:
				if other is not klass:
					if other.__name__.startswith( prefix ): hits += 1
			if hits >= 2:
				altname = name[ len(prefix) : ]

		funcs = _OOAPI_[ klass ]
		newklass = _rpythonic_generate_subclass_( altname, klass, funcs )
		klass._rpythonic_wrapper_class_ = newklass
		G[ name ] = newklass	# replace struct with wrapper
		if altname not in G: G[ altname ] = newklass	# safely define with nicer name
		elif altname != name: # odd cases, maybe a function that returns the object, almost never happens.
			print('WARN - not replacing something with struct wrapper:', G[altname] )


def _rpythonic_setup_return_wrappers():
	R = _rpythonic_function_
	for klass in _OOAPI_:
		if klass in _OOAPI_RETURNS_OBJECT_:
			for f in _OOAPI_RETURNS_OBJECT_[klass]:
				f.object_oriented = True
				if not f.return_wrapper:	# just in case the ctypes footer had already defined it, do not overwrite
					f.return_wrapper = klass._rpythonic_wrapper_class_


###############################################################
##						OLD META FUNC						##
###############################################################
def _rpythonic_function_( name, result=ctypes.c_void_p, args=[]):
	mname = '_metafunc_%s' %name
	exec( 'class %s( _rpythonic_metafunc_ ): pass' %mname )
	k = locals()[mname]
	return k( name, result, args )
_OOAPI_ = {}
_OOAPI_RETURNS_OBJECT_ = {}
class _rpythonic_metafunc_(object):
	def __init__(self, name, result=ctypes.c_void_p, args=[]):
		self.name = name
		self.result = result
		self.argtypes = []		# can dynamically change CFUNCTYPE trick
		self.argnames = []
		self.argtypestypes = []
		for i,arg in enumerate(args):
			n,t = arg
			if n in PYTHON_RESERVED_KEYWORDS: n = 'C_'+n
			if n in self.argnames: n = '%s%s' %(n,i)
			self.argnames.append( n )
			self.argtypes.append( t )
			self.argtypestypes.append( type(t) )		# precomputed for speed

		self.argnames = tuple( self.argnames )				# should never change
		self.numargs = len( self.argtypes )
		self.callbacks = [None] * self.numargs
		self.return_wrapper = None
		self.object_oriented = False
		self.function = None
		for cdll in _CTYPES_CDLLS:	# functions could be multiple libraries
			if hasattr(cdll, self.name):
				func = self.function = getattr(cdll, self.name )
				RPYTHONIC_WRAPPER_FUNCTIONS[ name ] = self
				break
		if not self.function:
			RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES.append( name )

		if self.function: self.reset()

	def change_argument_type( self, name, t ):
		idx = self.argnames.index( name )
		self.argtypes[ idx ] = t
		self.argtypestypes[ idx ] = type(t)
		self.function.argtypes = self.argtypes

	def reset(self):
		if self.argnames:
			a = ',' + '=None,'.join( self.argnames ) + '=None'
			b = ','.join( self.argnames )
		else: a = b = ''

		callmeth = eval( 'lambda self %s: self._call_( %s )' %(a,b) )
		setattr( self.__class__, '__call__', callmeth )

		self.function.restype = self.result
		self.function.argtypes = self.argtypes

		if type( self.result ) is PyCPointerType and type(self.result._type_) is PyCStructType:
			klass = self.result._type_
			if klass not in _OOAPI_RETURNS_OBJECT_: _OOAPI_RETURNS_OBJECT_[klass] = []
			_OOAPI_RETURNS_OBJECT_[klass].append( self )

		self.defaults = []
		for i in range( self.numargs ):
			T = self.argtypes[ i ]
			if type(T) is PyCFuncPtrType:
				p = T()	# func pointers can not be None
				self.defaults.append( p )
				self.callbacks[ i ] = p					# save reference
			elif T in (ctypes.c_int, ctypes.c_uint, ctypes.c_long, ctypes.c_ulong):
				self.defaults.append( 0 )
			elif T in (ctypes.c_float, ctypes.c_double):
				self.defaults.append( .0 )
			else: self.defaults.append( None )	# None is allowed for all other types

			## generate OO API ##
			if i == 0 and type(T) is PyCPointerType and type(T._type_) is PyCStructType:
				klass = T._type_
				if klass not in _OOAPI_: _OOAPI_[ klass ] = []
				_OOAPI_[ klass ].append( self )

	def _call_( self, *args ):			# allow flexible calling types
		cargs = list( self.defaults )
		for i,arg in enumerate(args):
			if isinstance( arg, _rpythonic_meta_ ): arg = arg.POINTER
			elif hasattr( arg, '_rpythonic_' ): arg = arg.POINTER		# workaround - instance from another module

			t = type(arg)
			k = self.argtypes[ i ]
			kt = self.argtypestypes[ i ]
			if arg is None and cargs[i] is not None:	# use user defaults, very rare cases
				continue

			elif t is bool and k is ctypes.c_int:
				if arg: cargs[i] = 1	#ctypes.c_int(1)
				else: cargs[i] = 0	#ctypes.c_int(0)

			elif t in (list,tuple):				# convert lists and tuples into array
				if kt is PyCArrayType:
					cargs[ i ] = k(*arg)
				elif kt is PyCStructType:
					if k._array_wrapper_: cargs[ i ] = k(arg)	# allow easy array init
					else: cargs[ i ] = k(*arg)							# allow multiple args
				elif kt is PyCPointerType:
					cargs[ i ] = _convert_nested_list_to_pointer( k, arg )
				else: assert 0

			elif isinstance( arg, ctypes._Pointer ) and t is not k and kt is PyCPointerType:
				cargs[ i ] = ctypes.cast( arg, k )		# generic's that need to be cast

			elif kt is PyCStructType and isinstance( arg, ctypes._Pointer ):
				cargs[ i ] = arg.contents	# fixed may25

			elif kt is PyCPointerType and not isinstance( arg, (ctypes._Pointer,CArgObject) ):
				if t in (int,float,bool): ptr = k( k._type_(arg) )
				elif t is str:
					if not _ISPYTHON2: arg = arg.encode('utf-8')	# encode to ascii in python3
					ptr = ctypes.create_string_buffer(arg)				# correct and pypy compatible
				elif t in (PyCStructType, PyCArrayType):
					ptr = ctypes.cast( ctypes.pointer( arg ), k )
				else:
					ptr = arg	# TODO print warning?
				cargs[ i ] = ptr

			elif kt is PyCFuncPtrType:
				if t.__name__ == 'CFunctionType': cargs[ i ] = arg		# assume outside holds pointer
				else:													# this is not safe #
					cargs[ i ] = self.callbacks[ i ] = k( arg )				# assume arg is a callable
			else:
				cargs[ i ] = arg		# directly pass

		## if you define your own return_wrapper, it must take keyword "pointer"
		if self.return_wrapper: return self.return_wrapper( pointer=self.function( *cargs ) )
		else: return self.function( *cargs )



def _convert_nested_list_to_pointer( k, arg ):
	depth = 0; s = k
	while True:
		if type(s) is PyCPointerType:
			s = getattr( s, '_type_' )
			depth += 1
		else: break
	assert depth and depth <= 2
	if depth == 1:
		T = k._type_
		ptr = k( k._type_() )
		for i in range( len(arg) ):
			ptr[ i ] = T( *arg[i] )
	elif depth == 2:
		T = k._type_._type_
		_ptr = k._type_( k._type_._type_() )
		for i in range(len( arg )):
			for j in range( len(arg[i]) ):
				_ptr[ j ] = T( *arg[ i ][ j ] )
		ptr = k( _ptr )
	return ptr


def __freeze_rpythonic_struct( cls, fields ):
	if cls not in _OOAPI_: _OOAPI_[ cls ] = []	# wrap all structs
	try: setattr( cls, '_fields_', fields )
	except:
		print( 'WARN - bad order struct freeze', cls )
		#cls._fields_ = []

class _rpythonic_struct_( ctypes.Structure ):
	_array_wrapper_ = False
	_fields_ = []
	_methods_ = {}
	#def __call__(self): return self
	def __init__(self, *args, **kw ):
		cargs = []
		argtypes = []
		for a in self._fields_: argtypes.append( a[1] )
		if len(args) > len(argtypes): args = [args]	# allow both calling conventions
		for i,arg in enumerate( args ):
			if isinstance( arg, _rpythonic_meta_ ): arg = arg.POINTER

			t = type(arg)
			k = argtypes[ i ]
			if t in (list,tuple):
				if k.__class__.__name__	== 'PyCArrayType':
					cargs.append( k(*arg) )
				elif k.__class__.__name__ == 'PyCStructType':
					if k._array_wrapper_: cargs.append( k(arg) )	# allow easy array init
					else: cargs.append( k(*arg) )							# allow multiple args
			elif isinstance( arg, ctypes._Pointer ) and t is not k:
				cargs[ i ] = ctypes.cast( arg, k )	# generic's that need to be cast
			elif k.__class__.__name__ == 'PyCArrayType' and t in (float,int,bool):
				cargs.append( k(arg) )		# support init array from single value
			else:
				cargs.append( arg )		# directly pass

		ctypes.Structure.__init__(self, *cargs, **kw)


def _rpythonic_make_nice_global_enums_():
	G = globals()
	for name in RPYTHONIC_GLOBAL_ENUMS:
		if '_' in name and name.index('_') <= 4:
			altname = name[ name.index('_') + 1 : ]
			if altname not in G:
				G[altname] = RPYTHONIC_GLOBAL_ENUMS[ name ]

def _rpythonic_clean_up_missing_functions_():
	G = globals()
	for f in RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES:
		G.pop( f )
	print( "C functions loaded: %s" %len(RPYTHONIC_WRAPPER_FUNCTIONS) )
	print( "C functions failed: %s" %len(RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES) )



###### NEW API #########
CTYPES_DLL = None

class _VOID_POINTER_CONTAINER_(object):
	def __init__(self, ptr, name=None):
		self._pointer_ = ptr
		self.name = name
NULL = _VOID_POINTER_CONTAINER_(None,'<null pointer>')


class meta:	# NEW API - allow run time switch from ctypes to rffi
	'''
	Methods:
		RPython will not allow object wrapper around a method (__call__ not allowed)
		keep C function names in list "__cfunctions__"
		rpythonic.enable_rffi( classA, classB )	
		can take advantage of methods in object-method-wrapper,
		generate rffi wrapper and set method on classA, etc.
		replaces object-method-wrapper with rffi-method

	Properties:
		CPython: obj.x=1
		RPython: obj.set_x(1)	
	'''
	METAS = []
	def __init__(self, constructors=[], methods={}, properties={}):
		#global CTYPES_DLL	# TODO update me to using _CTYPES_CDLLS
		#if not CTYPES_DLL:
		#	CTYPES_DLL = _load_ctypes_lib( _clib_name_ )

		self.constructors = constructors
		self.methods = methods
		self.properties = properties
		self.METAS.append( self )



	def __call__(self, cls ):
		print('@meta', cls )

		if not self.constructors:
			lamb = lambda s, _explicit_pointer_=None: setattr(s,'_pointer_',getattr(_explicit_pointer_,'_pointer_')) if hasattr(_explicit_pointer_,'_pointer_') else setattr(s,'_pointer_',_explicit_pointer_)
			lamb._debug = '(no constructor)'
			setattr( cls, '__init__', lamb )
		else:
			con = self._find_best_function( self.constructors )
			cfunc = self._build_cfunc( con )
			setattr( cls, '_%s'%con['name'], cfunc )
			g = self._gen_init( con )
			setattr( cls, '__init__', g )
		
		## set methods ##
		for name in self.methods:
			meth = self.methods[ name ]
			cfuncs = []
			for m in meth['functions']:
				cfunc = self._build_cfunc( m, method=True, static=meth['static'] )
				self._setup_return( cfunc, meth )
				setattr( cls, '_%s'%m['name'], cfunc )
				cfuncs.append( cfunc )

			f = self._find_best_function( meth['functions'] )
			g = self._gen_method( meth, f )
			g._cfuncs = cfuncs
			if meth['static']: g = classmethod( g )
			setattr( cls, name, g )

		for name in self.properties:
			print( 'property:', name )
			p = []
			for f in self.properties[name]:
				cfunc = self._build_cfunc( f )
				setattr( cls, '_%s'%f['name'], cfunc )
				g = self._gen_method( f, f )
				p.append( g )

			setattr( cls, name, property(*p) )

		return cls


	@staticmethod
	def _build_cfunc( info, method=False, static=False ):
		cfunc = getattr(CTYPES_DLL, info['name'])
		if method and not static: argtypes = [ ctypes.c_void_p ]
		else: argtypes = []
		for p in info['parameters']: argtypes.append( eval(p['ctypes_type']) )
		cfunc.argtypes = argtypes
		return cfunc

	@staticmethod
	def _setup_return( cfunc, info ):
		if not info['returns_fundamental']:
			cfunc.restype = ctypes.c_void_p
		elif info['returns_fundamental']:
			cfunc.restype = eval( info['returns_ctypes'] )
		else:
			cfunc.restype = ctypes.c_void_p

	@staticmethod
	def _gen_prepare_args( m ):
		a = []; b = []
		for i,p in enumerate(m['parameters']):
			if 'name' in p: n = p['name']
			else: n = '_unnamed_%s' %i
			if '<' in n: n = '_TODOfixme_%s' %i
			if n in PYTHON_RESERVED_KEYWORDS: n += str(i)
			if p['fundamental']:
				b.append( n )
				s = p['raw_type'].split()
				if 'default' in p:
					d = p['default']
					if p['raw_type'] in ('float', 'double'):
						if d.endswith('f'): d = d[:-1]
						d = d.replace(' ', '.')
						if 'e' in d: d = 0.0
						try: d = float(d)
						except: d = 0.0
					elif ('int' in s or 'size_t' in s) and not d.isdigit(): d = 0
					elif 'char' in s and '"' not in d: d = '""'
					elif d.lower() == 'false': d = False
					elif d.lower() == 'true': d = True
				elif 'char' in s: d = '""'
				elif 'float' in s or 'double' in s: d = 0.0
				elif 'size_t' in s or 'int' in s or 'long' in s or 'short' in s: d = 0
				elif p['raw_type'] == 'bool': d = False
				elif p['raw_type'] in ('void', '(template)'): d = 'NULL'
				else: print( p )
				a.append( n+'=%s' %d )

			else:
				b.append( '%s._pointer_'%n )
				a.append( n+'=NULL' )
		return a, b

	@staticmethod
	def _gen_init( m ):
		a, b = meta._gen_prepare_args( m )
		if a: e = 'lambda _py_self_, %s, _explicit_pointer_=None: ' %(','.join(a))
		else: e = 'lambda _py_self_, _explicit_pointer_=None: '
		e += 'setattr(_py_self_, "_pointer_", _py_self_._%s(%s))' %( m['name'], ','.join(b) )
		e += ' if not _explicit_pointer_ else '
		e += 'setattr(_py_self_, "_pointer_", _explicit_pointer_)'
		print( e )
		lamb = eval( e ); lamb._debug = e; lamb._introspect = m
		return lamb

	@staticmethod
	def _find_best_function( funcs ):
		best = funcs[0]
		score = -1
		if len(funcs) > 1:
			for f in funcs:
				hits = 0
				for p in f['parameters']:
					if p['fundamental']: hits += 1
				if hits and hits == len( f['parameters'] ):
					if hits > score:
						score = hits
						best = f
		return best

	@staticmethod
	def _gen_method( m, f ):
		a, b = meta._gen_prepare_args( f )
		if a: e = 'lambda _py_self_, %s: ' %(','.join(a))
		else: e = 'lambda _py_self_: '

		if 'static' in m and m['static']:	# static in c++ is like a classmethod
			c = '_py_self_._%s( %s )' %( f['name'], ','.join(b) )
		else:
			c = '_py_self_._%s( _py_self_._pointer_, %s )' %( f['name'], ','.join(b) )

		if not m['returns_fundamental']:
			if 'returns_unknown' in m or '<' in m['returns']: c = '_VOID_POINTER_CONTAINER_( %s, name="%s" )' %(c,m['returns'])
			else:
				something = m['returns'].replace('::', '.')
				c = '%s( _explicit_pointer_=%s )' %(something, c)

		e += c; lamb = eval( e )
		lamb._debug = e; lamb._introspect = f
		return lamb


	META_FUNCTIONS = []
	@classmethod
	def function( self, info ):
		print('@meta.function', info['name'] )
		#global CTYPES_DLL
		#if not CTYPES_DLL:
		#	CTYPES_DLL = _load_ctypes_lib( _clib_name_ )

		cfunc = self._build_cfunc( info, method=False, static=True )
		setattr( meta, '_%s'%info['name'], cfunc )
		self._setup_return( cfunc, info )
		a, b = meta._gen_prepare_args( info )
		e = 'lambda %s: ' %(','.join(a))
		c = 'meta._%s( %s )' %( info['name'], ','.join(b) )

		if not info['returns_fundamental']:
			if 'returns_unknown' in info or '<' in info['returns']:
				c = '_VOID_POINTER_CONTAINER_( %s, name="%s" )' %(c,info['returns'])
			else:
				something = info['returns'].replace('::', '.')
				c = '%s( _explicit_pointer_=%s )' %(something, c)
		e += c
		lamb = eval( e )
		lamb._debug = e
		lamb._introspect = info
		return lamb



def _rpythonic_strip_prefixes_( prefixes ):
	G = globals()
	names = list(G.keys())	# ensure list in py3
	for name in names:
		for prefix in prefixes:
			if name.startswith( prefix ):
				newname = name[ len(prefix) : ]
				if newname and newname not in G:
					G[ newname ] = G[ name ]


########################################################
##				Load Dynamic Libaries					##
def _rpythonic_load_dynamic_libraries(names):
	global _CTYPES_CDLLS
	for name in names:
		cdll = _load_ctypes_lib( name )
		if cdll:
			print('[[dynamic library loaded: %s]]' %name)
			_CTYPES_CDLLS.append( cdll )
#----------------------------------------------------------#
print( os.path.abspath( os.path.curdir ) )



_rpythonic_load_dynamic_libraries( ['libwayland-client'] )

## macro globals ##
WL_DISPLAY_READABLE = 1
WL_DISPLAY_WRITABLE = 2
## enums ##
FP_NAN = 0 
FP_INFINITE = 1 
FP_ZERO = 2 
FP_SUBNORMAL = 3 
FP_NORMAL = 4 

IEEE_ = -1 
SVID_ = 0 
XOPEN_ = 1 
POSIX_ = 2 
ISOC_ = 3 

wl_display_error = { 
	"WL_DISPLAY_ERROR_INVALID_OBJECT" : 0, 
	"WL_DISPLAY_ERROR_INVALID_METHOD" : 1, 
	"WL_DISPLAY_ERROR_NO_MEMORY" : 2, 
}

wl_shm_error = { 
	"WL_SHM_ERROR_INVALID_FORMAT" : 0, 
	"WL_SHM_ERROR_INVALID_STRIDE" : 1, 
	"WL_SHM_ERROR_INVALID_FD" : 2, 
}

wl_shm_format = { 
	"WL_SHM_FORMAT_ARGB8888" : 0, 
	"WL_SHM_FORMAT_XRGB8888" : 1, 
}

wl_shell_surface_resize = { 
	"WL_SHELL_SURFACE_RESIZE_NONE" : 0, 
	"WL_SHELL_SURFACE_RESIZE_TOP" : 1, 
	"WL_SHELL_SURFACE_RESIZE_BOTTOM" : 2, 
	"WL_SHELL_SURFACE_RESIZE_LEFT" : 4, 
	"WL_SHELL_SURFACE_RESIZE_TOP_LEFT" : 5, 
	"WL_SHELL_SURFACE_RESIZE_BOTTOM_LEFT" : 6, 
	"WL_SHELL_SURFACE_RESIZE_RIGHT" : 8, 
	"WL_SHELL_SURFACE_RESIZE_TOP_RIGHT" : 9, 
	"WL_SHELL_SURFACE_RESIZE_BOTTOM_RIGHT" : 10, 
}

wl_shell_surface_transient = { 
	"WL_SHELL_SURFACE_TRANSIENT_INACTIVE" : 1, 
}

wl_shell_surface_fullscreen_method = { 
	"WL_SHELL_SURFACE_FULLSCREEN_METHOD_DEFAULT" : 0, 
	"WL_SHELL_SURFACE_FULLSCREEN_METHOD_SCALE" : 1, 
	"WL_SHELL_SURFACE_FULLSCREEN_METHOD_DRIVER" : 2, 
	"WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL" : 3, 
}

wl_seat_capability = { 
	"WL_SEAT_CAPABILITY_POINTER" : 1, 
	"WL_SEAT_CAPABILITY_KEYBOARD" : 2, 
	"WL_SEAT_CAPABILITY_TOUCH" : 4, 
}

wl_pointer_button_state = { 
	"WL_POINTER_BUTTON_STATE_RELEASED" : 0, 
	"WL_POINTER_BUTTON_STATE_PRESSED" : 1, 
}

wl_pointer_axis = { 
	"WL_POINTER_AXIS_VERTICAL_SCROLL" : 0, 
	"WL_POINTER_AXIS_HORIZONTAL_SCROLL" : 1, 
}

wl_keyboard_keymap_format = { 
	"WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1" : 1, 
}

wl_keyboard_key_state = { 
	"WL_KEYBOARD_KEY_STATE_RELEASED" : 0, 
	"WL_KEYBOARD_KEY_STATE_PRESSED" : 1, 
	"WL_KEYBOARD_KEY_STATE_REPEAT" : 2, 
}

wl_output_subpixel = { 
	"WL_OUTPUT_SUBPIXEL_UNKNOWN" : 0, 
	"WL_OUTPUT_SUBPIXEL_NONE" : 1, 
	"WL_OUTPUT_SUBPIXEL_HORIZONTAL_RGB" : 2, 
	"WL_OUTPUT_SUBPIXEL_HORIZONTAL_BGR" : 3, 
	"WL_OUTPUT_SUBPIXEL_VERTICAL_RGB" : 4, 
	"WL_OUTPUT_SUBPIXEL_VERTICAL_BGR" : 5, 
}

wl_output_mode = { 
	"WL_OUTPUT_MODE_CURRENT" : 1, 
	"WL_OUTPUT_MODE_PREFERRED" : 2, 
}

## simple enums ##
RPYTHONIC_GLOBAL_ENUMS = { 
 "FP_NAN" : 0,  "FP_INFINITE" : 1,  "FP_ZERO" : 2,  "FP_SUBNORMAL" : 3,  "FP_NORMAL" : 4, 
 "IEEE_" : -1,  "SVID_" : 0,  "XOPEN_" : 1,  "POSIX_" : 2,  "ISOC_" : 3, 

}
class exception(_rpythonic_struct_): pass
class imaxdiv_t(_rpythonic_struct_): pass
class wl_message(_rpythonic_struct_): pass
class wl_interface(_rpythonic_struct_): pass
class wl_object(_rpythonic_struct_): pass
class wl_list(_rpythonic_struct_): pass
class wl_array(_rpythonic_struct_): pass
class wl_proxy(_rpythonic_struct_): pass
class wl_display(_rpythonic_struct_): pass
class wl_callback(_rpythonic_struct_): pass
class wl_client(_rpythonic_struct_): pass
class wl_resource(_rpythonic_struct_): pass
class wl_compositor(_rpythonic_struct_): pass
class wl_shm_pool(_rpythonic_struct_): pass
class wl_shm(_rpythonic_struct_): pass
class wl_buffer(_rpythonic_struct_): pass
class wl_data_offer(_rpythonic_struct_): pass
class wl_data_source(_rpythonic_struct_): pass
class wl_data_device(_rpythonic_struct_): pass
class wl_data_device_manager(_rpythonic_struct_): pass
class wl_shell(_rpythonic_struct_): pass
class wl_shell_surface(_rpythonic_struct_): pass
class wl_surface(_rpythonic_struct_): pass
class wl_seat(_rpythonic_struct_): pass
class wl_pointer(_rpythonic_struct_): pass
class wl_keyboard(_rpythonic_struct_): pass
class wl_touch(_rpythonic_struct_): pass
class wl_output(_rpythonic_struct_): pass
class wl_region(_rpythonic_struct_): pass
class wl_display_listener(_rpythonic_struct_): pass
class wl_callback_listener(_rpythonic_struct_): pass
class wl_shm_listener(_rpythonic_struct_): pass
class wl_buffer_listener(_rpythonic_struct_): pass
class wl_data_offer_listener(_rpythonic_struct_): pass
class wl_data_source_listener(_rpythonic_struct_): pass
class wl_data_device_listener(_rpythonic_struct_): pass
class wl_shell_surface_listener(_rpythonic_struct_): pass
class wl_surface_listener(_rpythonic_struct_): pass
class wl_seat_listener(_rpythonic_struct_): pass
class wl_pointer_listener(_rpythonic_struct_): pass
class wl_keyboard_listener(_rpythonic_struct_): pass
class wl_touch_listener(_rpythonic_struct_): pass
class wl_output_listener(_rpythonic_struct_): pass
class wl_global_listener(_rpythonic_struct_): pass
## union and structures ##
__freeze_rpythonic_struct( exception, [
	( "C_type", ctypes.c_int ),
	( "name", ctypes.POINTER(ctypes.c_char) ),
	( "arg1", ctypes.c_double ),
	( "arg2", ctypes.c_double ),
	( "retval", ctypes.c_double ),
])

__freeze_rpythonic_struct( imaxdiv_t, [
	( "quot", ctypes.c_int64 ),
	( "rem", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( wl_message, [
	( "name", ctypes.POINTER(ctypes.c_char) ),
	( "signature", ctypes.POINTER(ctypes.c_char) ),
	( "types", ctypes.POINTER(ctypes.POINTER(wl_interface)) ),
])

__freeze_rpythonic_struct( wl_interface, [
	( "name", ctypes.POINTER(ctypes.c_char) ),
	( "version", ctypes.c_int ),
	( "method_count", ctypes.c_int ),
	( "methods", ctypes.POINTER(wl_message) ),
	( "event_count", ctypes.c_int ),
	( "events", ctypes.POINTER(wl_message) ),
])

__freeze_rpythonic_struct( wl_object, [
	( "interface", ctypes.POINTER(wl_interface) ),
	( "implementation", ctypes.POINTER(ctypes.c_void_p) ),
	( "C_id", ctypes.c_uint32 ),
])

__freeze_rpythonic_struct( wl_list, [
	( "prev", ctypes.POINTER(wl_list) ),
	( "next", ctypes.POINTER(wl_list) ),
])

__freeze_rpythonic_struct( wl_array, [
	( "size", ctypes.c_uint64 ),
	( "alloc", ctypes.c_uint64 ),
	( "data", ctypes.POINTER(ctypes.c_void_p) ),
])

__freeze_rpythonic_struct( wl_proxy, [
])

__freeze_rpythonic_struct( wl_display, [
])

__freeze_rpythonic_struct( wl_callback, [
])

__freeze_rpythonic_struct( wl_client, [
])

__freeze_rpythonic_struct( wl_resource, [
])

__freeze_rpythonic_struct( wl_compositor, [
])

__freeze_rpythonic_struct( wl_shm_pool, [
])

__freeze_rpythonic_struct( wl_shm, [
])

__freeze_rpythonic_struct( wl_buffer, [
])

__freeze_rpythonic_struct( wl_data_offer, [
])

__freeze_rpythonic_struct( wl_data_source, [
])

__freeze_rpythonic_struct( wl_data_device, [
])

__freeze_rpythonic_struct( wl_data_device_manager, [
])

__freeze_rpythonic_struct( wl_shell, [
])

__freeze_rpythonic_struct( wl_shell_surface, [
])

__freeze_rpythonic_struct( wl_surface, [
])

__freeze_rpythonic_struct( wl_seat, [
])

__freeze_rpythonic_struct( wl_pointer, [
])

__freeze_rpythonic_struct( wl_keyboard, [
])

__freeze_rpythonic_struct( wl_touch, [
])

__freeze_rpythonic_struct( wl_output, [
])

__freeze_rpythonic_struct( wl_region, [
])

__freeze_rpythonic_struct( wl_display_listener, [
	( "error", ctypes.c_void_p ),
	( "C_global", ctypes.c_void_p ),
	( "global_remove", ctypes.c_void_p ),
	( "delete_id", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_callback_listener, [
	( "done", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_shm_listener, [
	( "format", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_buffer_listener, [
	( "release", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_data_offer_listener, [
	( "offer", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_data_source_listener, [
	( "target", ctypes.c_void_p ),
	( "send", ctypes.c_void_p ),
	( "cancelled", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_data_device_listener, [
	( "data_offer", ctypes.c_void_p ),
	( "enter", ctypes.c_void_p ),
	( "leave", ctypes.c_void_p ),
	( "motion", ctypes.c_void_p ),
	( "drop", ctypes.c_void_p ),
	( "selection", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_shell_surface_listener, [
	( "ping", ctypes.c_void_p ),
	( "configure", ctypes.c_void_p ),
	( "popup_done", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_surface_listener, [
	( "enter", ctypes.c_void_p ),
	( "leave", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_seat_listener, [
	( "capabilities", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_pointer_listener, [
	( "enter", ctypes.c_void_p ),
	( "leave", ctypes.c_void_p ),
	( "motion", ctypes.c_void_p ),
	( "button", ctypes.c_void_p ),
	( "axis", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_keyboard_listener, [
	( "keymap", ctypes.c_void_p ),
	( "enter", ctypes.c_void_p ),
	( "leave", ctypes.c_void_p ),
	( "key", ctypes.c_void_p ),
	( "modifiers", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_touch_listener, [
	( "down", ctypes.c_void_p ),
	( "up", ctypes.c_void_p ),
	( "motion", ctypes.c_void_p ),
	( "frame", ctypes.c_void_p ),
	( "cancel", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_output_listener, [
	( "geometry", ctypes.c_void_p ),
	( "mode", ctypes.c_void_p ),
])

__freeze_rpythonic_struct( wl_global_listener, [
])

## wrapper functions ##
acos = _rpythonic_function_(		"acos", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

asin = _rpythonic_function_(		"asin", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

atan = _rpythonic_function_(		"atan", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

atan2 = _rpythonic_function_(		"atan2", ctypes.c_double, [
	("__y",		ctypes.c_double),
	("__x",		ctypes.c_double),] )

cos = _rpythonic_function_(		"cos", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

sin = _rpythonic_function_(		"sin", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

tan = _rpythonic_function_(		"tan", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

cosh = _rpythonic_function_(		"cosh", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

sinh = _rpythonic_function_(		"sinh", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

tanh = _rpythonic_function_(		"tanh", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

acosh = _rpythonic_function_(		"acosh", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

asinh = _rpythonic_function_(		"asinh", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

atanh = _rpythonic_function_(		"atanh", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

exp = _rpythonic_function_(		"exp", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

frexp = _rpythonic_function_(		"frexp", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__exponent",		ctypes.POINTER(ctypes.c_int)),] )

ldexp = _rpythonic_function_(		"ldexp", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__exponent",		ctypes.c_int),] )

log = _rpythonic_function_(		"log", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

log10 = _rpythonic_function_(		"log10", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

modf = _rpythonic_function_(		"modf", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__iptr",		ctypes.POINTER(ctypes.c_double)),] )

expm1 = _rpythonic_function_(		"expm1", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

log1p = _rpythonic_function_(		"log1p", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

logb = _rpythonic_function_(		"logb", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

exp2 = _rpythonic_function_(		"exp2", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

log2 = _rpythonic_function_(		"log2", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

pow = _rpythonic_function_(		"pow", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

sqrt = _rpythonic_function_(		"sqrt", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

hypot = _rpythonic_function_(		"hypot", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

cbrt = _rpythonic_function_(		"cbrt", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

ceil = _rpythonic_function_(		"ceil", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

fabs = _rpythonic_function_(		"fabs", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

floor = _rpythonic_function_(		"floor", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

fmod = _rpythonic_function_(		"fmod", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

isinf = _rpythonic_function_(		"isinf", ctypes.c_int, [
	("__value",		ctypes.c_double),] )

finite = _rpythonic_function_(		"finite", ctypes.c_int, [
	("__value",		ctypes.c_double),] )

drem = _rpythonic_function_(		"drem", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

significand = _rpythonic_function_(		"significand", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

copysign = _rpythonic_function_(		"copysign", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

nan = _rpythonic_function_(		"nan", ctypes.c_double, [
	("__tagb",		ctypes.POINTER(ctypes.c_char)),] )

isnan = _rpythonic_function_(		"isnan", ctypes.c_int, [
	("__value",		ctypes.c_double),] )

j0 = _rpythonic_function_(		"j0", ctypes.c_double, [
	("none",		ctypes.c_double),] )

j1 = _rpythonic_function_(		"j1", ctypes.c_double, [
	("none",		ctypes.c_double),] )

jn = _rpythonic_function_(		"jn", ctypes.c_double, [
	("none",		ctypes.c_int),
	("none",		ctypes.c_double),] )

y0 = _rpythonic_function_(		"y0", ctypes.c_double, [
	("none",		ctypes.c_double),] )

y1 = _rpythonic_function_(		"y1", ctypes.c_double, [
	("none",		ctypes.c_double),] )

yn = _rpythonic_function_(		"yn", ctypes.c_double, [
	("none",		ctypes.c_int),
	("none",		ctypes.c_double),] )

erf = _rpythonic_function_(		"erf", ctypes.c_double, [
	("none",		ctypes.c_double),] )

erfc = _rpythonic_function_(		"erfc", ctypes.c_double, [
	("none",		ctypes.c_double),] )

lgamma = _rpythonic_function_(		"lgamma", ctypes.c_double, [
	("none",		ctypes.c_double),] )

tgamma = _rpythonic_function_(		"tgamma", ctypes.c_double, [
	("none",		ctypes.c_double),] )

gamma = _rpythonic_function_(		"gamma", ctypes.c_double, [
	("none",		ctypes.c_double),] )

lgamma_r = _rpythonic_function_(		"lgamma_r", ctypes.c_double, [
	("none",		ctypes.c_double),
	("__signgamp",		ctypes.POINTER(ctypes.c_int)),] )

rint = _rpythonic_function_(		"rint", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

nextafter = _rpythonic_function_(		"nextafter", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

nexttoward = _rpythonic_function_(		"nexttoward", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

remainder = _rpythonic_function_(		"remainder", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

scalbn = _rpythonic_function_(		"scalbn", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__n",		ctypes.c_int),] )

ilogb = _rpythonic_function_(		"ilogb", ctypes.c_int, [
	("__x",		ctypes.c_double),] )

scalbln = _rpythonic_function_(		"scalbln", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__n",		ctypes.c_int64),] )

nearbyint = _rpythonic_function_(		"nearbyint", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

round = _rpythonic_function_(		"round", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

trunc = _rpythonic_function_(		"trunc", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

remquo = _rpythonic_function_(		"remquo", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),
	("__quo",		ctypes.POINTER(ctypes.c_int)),] )

lrint = _rpythonic_function_(		"lrint", ctypes.c_int64, [
	("__x",		ctypes.c_double),] )

llrint = _rpythonic_function_(		"llrint", ctypes.c_longlong, [
	("__x",		ctypes.c_double),] )

lround = _rpythonic_function_(		"lround", ctypes.c_int64, [
	("__x",		ctypes.c_double),] )

llround = _rpythonic_function_(		"llround", ctypes.c_longlong, [
	("__x",		ctypes.c_double),] )

fdim = _rpythonic_function_(		"fdim", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

fmax = _rpythonic_function_(		"fmax", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

fmin = _rpythonic_function_(		"fmin", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

fma = _rpythonic_function_(		"fma", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),
	("__z",		ctypes.c_double),] )

scalb = _rpythonic_function_(		"scalb", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__n",		ctypes.c_double),] )

acosf = _rpythonic_function_(		"acosf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

asinf = _rpythonic_function_(		"asinf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

atanf = _rpythonic_function_(		"atanf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

atan2f = _rpythonic_function_(		"atan2f", ctypes.c_float, [
	("__y",		ctypes.c_float),
	("__x",		ctypes.c_float),] )

cosf = _rpythonic_function_(		"cosf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

sinf = _rpythonic_function_(		"sinf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

tanf = _rpythonic_function_(		"tanf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

coshf = _rpythonic_function_(		"coshf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

sinhf = _rpythonic_function_(		"sinhf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

tanhf = _rpythonic_function_(		"tanhf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

acoshf = _rpythonic_function_(		"acoshf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

asinhf = _rpythonic_function_(		"asinhf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

atanhf = _rpythonic_function_(		"atanhf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

expf = _rpythonic_function_(		"expf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

frexpf = _rpythonic_function_(		"frexpf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__exponent",		ctypes.POINTER(ctypes.c_int)),] )

ldexpf = _rpythonic_function_(		"ldexpf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__exponent",		ctypes.c_int),] )

logf = _rpythonic_function_(		"logf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

log10f = _rpythonic_function_(		"log10f", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

modff = _rpythonic_function_(		"modff", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__iptr",		ctypes.POINTER(ctypes.c_float)),] )

expm1f = _rpythonic_function_(		"expm1f", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

log1pf = _rpythonic_function_(		"log1pf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

logbf = _rpythonic_function_(		"logbf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

exp2f = _rpythonic_function_(		"exp2f", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

log2f = _rpythonic_function_(		"log2f", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

powf = _rpythonic_function_(		"powf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

sqrtf = _rpythonic_function_(		"sqrtf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

hypotf = _rpythonic_function_(		"hypotf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

cbrtf = _rpythonic_function_(		"cbrtf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

ceilf = _rpythonic_function_(		"ceilf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

fabsf = _rpythonic_function_(		"fabsf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

floorf = _rpythonic_function_(		"floorf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

fmodf = _rpythonic_function_(		"fmodf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

isinff = _rpythonic_function_(		"isinff", ctypes.c_int, [
	("__value",		ctypes.c_float),] )

finitef = _rpythonic_function_(		"finitef", ctypes.c_int, [
	("__value",		ctypes.c_float),] )

dremf = _rpythonic_function_(		"dremf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

significandf = _rpythonic_function_(		"significandf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

copysignf = _rpythonic_function_(		"copysignf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

nanf = _rpythonic_function_(		"nanf", ctypes.c_float, [
	("__tagb",		ctypes.POINTER(ctypes.c_char)),] )

isnanf = _rpythonic_function_(		"isnanf", ctypes.c_int, [
	("__value",		ctypes.c_float),] )

j0f = _rpythonic_function_(		"j0f", ctypes.c_float, [
	("none",		ctypes.c_float),] )

j1f = _rpythonic_function_(		"j1f", ctypes.c_float, [
	("none",		ctypes.c_float),] )

jnf = _rpythonic_function_(		"jnf", ctypes.c_float, [
	("none",		ctypes.c_int),
	("none",		ctypes.c_float),] )

y0f = _rpythonic_function_(		"y0f", ctypes.c_float, [
	("none",		ctypes.c_float),] )

y1f = _rpythonic_function_(		"y1f", ctypes.c_float, [
	("none",		ctypes.c_float),] )

ynf = _rpythonic_function_(		"ynf", ctypes.c_float, [
	("none",		ctypes.c_int),
	("none",		ctypes.c_float),] )

erff = _rpythonic_function_(		"erff", ctypes.c_float, [
	("none",		ctypes.c_float),] )

erfcf = _rpythonic_function_(		"erfcf", ctypes.c_float, [
	("none",		ctypes.c_float),] )

lgammaf = _rpythonic_function_(		"lgammaf", ctypes.c_float, [
	("none",		ctypes.c_float),] )

tgammaf = _rpythonic_function_(		"tgammaf", ctypes.c_float, [
	("none",		ctypes.c_float),] )

gammaf = _rpythonic_function_(		"gammaf", ctypes.c_float, [
	("none",		ctypes.c_float),] )

lgammaf_r = _rpythonic_function_(		"lgammaf_r", ctypes.c_float, [
	("none",		ctypes.c_float),
	("__signgamp",		ctypes.POINTER(ctypes.c_int)),] )

rintf = _rpythonic_function_(		"rintf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

nextafterf = _rpythonic_function_(		"nextafterf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

nexttowardf = _rpythonic_function_(		"nexttowardf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_double),] )

remainderf = _rpythonic_function_(		"remainderf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

scalbnf = _rpythonic_function_(		"scalbnf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__n",		ctypes.c_int),] )

ilogbf = _rpythonic_function_(		"ilogbf", ctypes.c_int, [
	("__x",		ctypes.c_float),] )

scalblnf = _rpythonic_function_(		"scalblnf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__n",		ctypes.c_int64),] )

nearbyintf = _rpythonic_function_(		"nearbyintf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

roundf = _rpythonic_function_(		"roundf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

truncf = _rpythonic_function_(		"truncf", ctypes.c_float, [
	("__x",		ctypes.c_float),] )

remquof = _rpythonic_function_(		"remquof", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),
	("__quo",		ctypes.POINTER(ctypes.c_int)),] )

lrintf = _rpythonic_function_(		"lrintf", ctypes.c_int64, [
	("__x",		ctypes.c_float),] )

llrintf = _rpythonic_function_(		"llrintf", ctypes.c_longlong, [
	("__x",		ctypes.c_float),] )

lroundf = _rpythonic_function_(		"lroundf", ctypes.c_int64, [
	("__x",		ctypes.c_float),] )

llroundf = _rpythonic_function_(		"llroundf", ctypes.c_longlong, [
	("__x",		ctypes.c_float),] )

fdimf = _rpythonic_function_(		"fdimf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

fmaxf = _rpythonic_function_(		"fmaxf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

fminf = _rpythonic_function_(		"fminf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),] )

fmaf = _rpythonic_function_(		"fmaf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__y",		ctypes.c_float),
	("__z",		ctypes.c_float),] )

scalbf = _rpythonic_function_(		"scalbf", ctypes.c_float, [
	("__x",		ctypes.c_float),
	("__n",		ctypes.c_float),] )

acosl = _rpythonic_function_(		"acosl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

asinl = _rpythonic_function_(		"asinl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

atanl = _rpythonic_function_(		"atanl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

atan2l = _rpythonic_function_(		"atan2l", ctypes.c_double, [
	("__y",		ctypes.c_double),
	("__x",		ctypes.c_double),] )

cosl = _rpythonic_function_(		"cosl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

sinl = _rpythonic_function_(		"sinl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

tanl = _rpythonic_function_(		"tanl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

coshl = _rpythonic_function_(		"coshl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

sinhl = _rpythonic_function_(		"sinhl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

tanhl = _rpythonic_function_(		"tanhl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

acoshl = _rpythonic_function_(		"acoshl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

asinhl = _rpythonic_function_(		"asinhl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

atanhl = _rpythonic_function_(		"atanhl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

expl = _rpythonic_function_(		"expl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

frexpl = _rpythonic_function_(		"frexpl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__exponent",		ctypes.POINTER(ctypes.c_int)),] )

ldexpl = _rpythonic_function_(		"ldexpl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__exponent",		ctypes.c_int),] )

logl = _rpythonic_function_(		"logl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

log10l = _rpythonic_function_(		"log10l", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

modfl = _rpythonic_function_(		"modfl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__iptr",		ctypes.POINTER(ctypes.c_double)),] )

expm1l = _rpythonic_function_(		"expm1l", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

log1pl = _rpythonic_function_(		"log1pl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

logbl = _rpythonic_function_(		"logbl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

exp2l = _rpythonic_function_(		"exp2l", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

log2l = _rpythonic_function_(		"log2l", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

powl = _rpythonic_function_(		"powl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

sqrtl = _rpythonic_function_(		"sqrtl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

hypotl = _rpythonic_function_(		"hypotl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

cbrtl = _rpythonic_function_(		"cbrtl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

ceill = _rpythonic_function_(		"ceill", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

fabsl = _rpythonic_function_(		"fabsl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

floorl = _rpythonic_function_(		"floorl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

fmodl = _rpythonic_function_(		"fmodl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

isinfl = _rpythonic_function_(		"isinfl", ctypes.c_int, [
	("__value",		ctypes.c_double),] )

finitel = _rpythonic_function_(		"finitel", ctypes.c_int, [
	("__value",		ctypes.c_double),] )

dreml = _rpythonic_function_(		"dreml", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

significandl = _rpythonic_function_(		"significandl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

copysignl = _rpythonic_function_(		"copysignl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

nanl = _rpythonic_function_(		"nanl", ctypes.c_double, [
	("__tagb",		ctypes.POINTER(ctypes.c_char)),] )

isnanl = _rpythonic_function_(		"isnanl", ctypes.c_int, [
	("__value",		ctypes.c_double),] )

j0l = _rpythonic_function_(		"j0l", ctypes.c_double, [
	("none",		ctypes.c_double),] )

j1l = _rpythonic_function_(		"j1l", ctypes.c_double, [
	("none",		ctypes.c_double),] )

jnl = _rpythonic_function_(		"jnl", ctypes.c_double, [
	("none",		ctypes.c_int),
	("none",		ctypes.c_double),] )

y0l = _rpythonic_function_(		"y0l", ctypes.c_double, [
	("none",		ctypes.c_double),] )

y1l = _rpythonic_function_(		"y1l", ctypes.c_double, [
	("none",		ctypes.c_double),] )

ynl = _rpythonic_function_(		"ynl", ctypes.c_double, [
	("none",		ctypes.c_int),
	("none",		ctypes.c_double),] )

erfl = _rpythonic_function_(		"erfl", ctypes.c_double, [
	("none",		ctypes.c_double),] )

erfcl = _rpythonic_function_(		"erfcl", ctypes.c_double, [
	("none",		ctypes.c_double),] )

lgammal = _rpythonic_function_(		"lgammal", ctypes.c_double, [
	("none",		ctypes.c_double),] )

tgammal = _rpythonic_function_(		"tgammal", ctypes.c_double, [
	("none",		ctypes.c_double),] )

gammal = _rpythonic_function_(		"gammal", ctypes.c_double, [
	("none",		ctypes.c_double),] )

lgammal_r = _rpythonic_function_(		"lgammal_r", ctypes.c_double, [
	("none",		ctypes.c_double),
	("__signgamp",		ctypes.POINTER(ctypes.c_int)),] )

rintl = _rpythonic_function_(		"rintl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

nextafterl = _rpythonic_function_(		"nextafterl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

nexttowardl = _rpythonic_function_(		"nexttowardl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

remainderl = _rpythonic_function_(		"remainderl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

scalbnl = _rpythonic_function_(		"scalbnl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__n",		ctypes.c_int),] )

ilogbl = _rpythonic_function_(		"ilogbl", ctypes.c_int, [
	("__x",		ctypes.c_double),] )

scalblnl = _rpythonic_function_(		"scalblnl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__n",		ctypes.c_int64),] )

nearbyintl = _rpythonic_function_(		"nearbyintl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

roundl = _rpythonic_function_(		"roundl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

truncl = _rpythonic_function_(		"truncl", ctypes.c_double, [
	("__x",		ctypes.c_double),] )

remquol = _rpythonic_function_(		"remquol", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),
	("__quo",		ctypes.POINTER(ctypes.c_int)),] )

lrintl = _rpythonic_function_(		"lrintl", ctypes.c_int64, [
	("__x",		ctypes.c_double),] )

llrintl = _rpythonic_function_(		"llrintl", ctypes.c_longlong, [
	("__x",		ctypes.c_double),] )

lroundl = _rpythonic_function_(		"lroundl", ctypes.c_int64, [
	("__x",		ctypes.c_double),] )

llroundl = _rpythonic_function_(		"llroundl", ctypes.c_longlong, [
	("__x",		ctypes.c_double),] )

fdiml = _rpythonic_function_(		"fdiml", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

fmaxl = _rpythonic_function_(		"fmaxl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

fminl = _rpythonic_function_(		"fminl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),] )

fmal = _rpythonic_function_(		"fmal", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__y",		ctypes.c_double),
	("__z",		ctypes.c_double),] )

scalbl = _rpythonic_function_(		"scalbl", ctypes.c_double, [
	("__x",		ctypes.c_double),
	("__n",		ctypes.c_double),] )

matherr = _rpythonic_function_(		"matherr", ctypes.c_int, [
	("__exc",		ctypes.POINTER(exception)),] )

imaxabs = _rpythonic_function_(		"imaxabs", ctypes.c_int64, [
	("__n",		ctypes.c_int64),] )

imaxdiv = _rpythonic_function_(		"imaxdiv", imaxdiv_t, [
	("__numer",		ctypes.c_int64),
	("__denom",		ctypes.c_int64),] )

strtoimax = _rpythonic_function_(		"strtoimax", ctypes.c_int64, [
	("__nptr",		ctypes.POINTER(ctypes.c_char)),
	("__endptr",		ctypes.POINTER(ctypes.POINTER(ctypes.c_char))),
	("__base",		ctypes.c_int),] )

strtoumax = _rpythonic_function_(		"strtoumax", ctypes.c_uint64, [
	("__nptr",		ctypes.POINTER(ctypes.c_char)),
	("__endptr",		ctypes.POINTER(ctypes.POINTER(ctypes.c_char))),
	("__base",		ctypes.c_int),] )

wcstoimax = _rpythonic_function_(		"wcstoimax", ctypes.c_int64, [
	("__nptr",		ctypes.POINTER(ctypes.c_int)),
	("__endptr",		ctypes.POINTER(ctypes.POINTER(ctypes.c_int))),
	("__base",		ctypes.c_int),] )

wcstoumax = _rpythonic_function_(		"wcstoumax", ctypes.c_uint64, [
	("__nptr",		ctypes.POINTER(ctypes.c_int)),
	("__endptr",		ctypes.POINTER(ctypes.POINTER(ctypes.c_int))),
	("__base",		ctypes.c_int),] )

implementation = _rpythonic_function_(		"implementation", ctypes.c_void_p, [] )

wl_list_init = _rpythonic_function_(		"wl_list_init", ctypes.c_void_p, [
	("C_list",		ctypes.POINTER(wl_list)),] )

wl_list_insert = _rpythonic_function_(		"wl_list_insert", ctypes.c_void_p, [
	("C_list",		ctypes.POINTER(wl_list)),
	("elm",		ctypes.POINTER(wl_list)),] )

wl_list_remove = _rpythonic_function_(		"wl_list_remove", ctypes.c_void_p, [
	("elm",		ctypes.POINTER(wl_list)),] )

wl_list_length = _rpythonic_function_(		"wl_list_length", ctypes.c_int, [
	("C_list",		ctypes.POINTER(wl_list)),] )

wl_list_empty = _rpythonic_function_(		"wl_list_empty", ctypes.c_int, [
	("C_list",		ctypes.POINTER(wl_list)),] )

wl_list_insert_list = _rpythonic_function_(		"wl_list_insert_list", ctypes.c_void_p, [
	("C_list",		ctypes.POINTER(wl_list)),
	("other",		ctypes.POINTER(wl_list)),] )

wl_array_init = _rpythonic_function_(		"wl_array_init", ctypes.c_void_p, [
	("array",		ctypes.POINTER(wl_array)),] )

wl_array_release = _rpythonic_function_(		"wl_array_release", ctypes.c_void_p, [
	("array",		ctypes.POINTER(wl_array)),] )

wl_array_add = _rpythonic_function_(		"wl_array_add", ctypes.POINTER(ctypes.c_void_p), [
	("array",		ctypes.POINTER(wl_array)),
	("size",		ctypes.c_uint64),] )

wl_array_copy = _rpythonic_function_(		"wl_array_copy", ctypes.c_void_p, [
	("array",		ctypes.POINTER(wl_array)),
	("source",		ctypes.POINTER(wl_array)),] )

wl_log_func_t = _rpythonic_function_(		"wl_log_func_t", ctypes.c_void_p, [
	("none",		ctypes.POINTER(ctypes.c_char)),
	("none",		ctypes.c_char),] )

wl_proxy_create = _rpythonic_function_(		"wl_proxy_create", ctypes.POINTER(wl_proxy), [
	("factory",		ctypes.POINTER(wl_proxy)),
	("interface",		ctypes.POINTER(wl_interface)),] )

wl_proxy_get_user_data = _rpythonic_function_(		"wl_proxy_get_user_data", ctypes.POINTER(ctypes.c_void_p), [
	("proxy",		ctypes.POINTER(wl_proxy)),] )

wl_proxy_get_id = _rpythonic_function_(		"wl_proxy_get_id", ctypes.c_uint32, [
	("proxy",		ctypes.POINTER(wl_proxy)),] )

wl_display_bind = _rpythonic_function_(		"wl_display_bind", ctypes.POINTER(ctypes.c_void_p), [
	("display",		ctypes.POINTER(wl_display)),
	("name",		ctypes.c_uint32),
	("interface",		ctypes.POINTER(wl_interface)),] )

wl_proxy_create_for_id = _rpythonic_function_(		"wl_proxy_create_for_id", ctypes.POINTER(wl_proxy), [
	("factory",		ctypes.POINTER(wl_proxy)),
	("C_id",		ctypes.c_uint32),
	("interface",		ctypes.POINTER(wl_interface)),] )

wl_proxy_destroy = _rpythonic_function_(		"wl_proxy_destroy", ctypes.c_void_p, [
	("proxy",		ctypes.POINTER(wl_proxy)),] )

wl_proxy_add_listener = _rpythonic_function_(		"wl_proxy_add_listener", ctypes.c_int, [
	("proxy",		ctypes.POINTER(wl_proxy)),
	("implementation",		ctypes.POINTER(ctypes.c_void_p)),
	("data",		ctypes.POINTER(ctypes.c_void_p)),] )

wl_proxy_set_user_data = _rpythonic_function_(		"wl_proxy_set_user_data", ctypes.c_void_p, [
	("proxy",		ctypes.POINTER(wl_proxy)),
	("user_data",		ctypes.POINTER(ctypes.c_void_p)),] )

wl_display_sync = _rpythonic_function_(		"wl_display_sync", ctypes.POINTER(wl_callback), [
	("display",		ctypes.POINTER(wl_display)),] )

error = _rpythonic_function_(		"error", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_display",		ctypes.POINTER(wl_display)),
	("object_id",		ctypes.POINTER(wl_object)),
	("code",		ctypes.c_uint32),
	("message",		ctypes.POINTER(ctypes.c_char)),] )

C_global = _rpythonic_function_(		"C_global", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_display",		ctypes.POINTER(wl_display)),
	("name",		ctypes.c_uint32),
	("interface",		ctypes.POINTER(ctypes.c_char)),
	("version",		ctypes.c_uint32),] )

global_remove = _rpythonic_function_(		"global_remove", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_display",		ctypes.POINTER(wl_display)),
	("name",		ctypes.c_uint32),] )

delete_id = _rpythonic_function_(		"delete_id", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_display",		ctypes.POINTER(wl_display)),
	("C_id",		ctypes.c_uint32),] )

done = _rpythonic_function_(		"done", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_callback",		ctypes.POINTER(wl_callback)),
	("serial",		ctypes.c_uint32),] )

format = _rpythonic_function_(		"format", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_shm",		ctypes.POINTER(wl_shm)),
	("format",		ctypes.c_uint32),] )

release = _rpythonic_function_(		"release", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_buffer",		ctypes.POINTER(wl_buffer)),] )

offer = _rpythonic_function_(		"offer", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_offer",		ctypes.POINTER(wl_data_offer)),
	("C_type",		ctypes.POINTER(ctypes.c_char)),] )

target = _rpythonic_function_(		"target", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_source",		ctypes.POINTER(wl_data_source)),
	("mime_type",		ctypes.POINTER(ctypes.c_char)),] )

data_offer = _rpythonic_function_(		"data_offer", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_device",		ctypes.POINTER(wl_data_device)),
	("C_id",		ctypes.POINTER(wl_data_offer)),] )

enter = _rpythonic_function_(		"enter", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_device",		ctypes.POINTER(wl_data_device)),
	("serial",		ctypes.c_uint32),
	("surface",		ctypes.POINTER(wl_surface)),
	("x",		ctypes.c_int32),
	("y",		ctypes.c_int32),
	("C_id",		ctypes.POINTER(wl_data_offer)),] )

send = _rpythonic_function_(		"send", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_source",		ctypes.POINTER(wl_data_source)),
	("mime_type",		ctypes.POINTER(ctypes.c_char)),
	("fd",		ctypes.c_int32),] )

cancelled = _rpythonic_function_(		"cancelled", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_source",		ctypes.POINTER(wl_data_source)),] )

leave = _rpythonic_function_(		"leave", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_device",		ctypes.POINTER(wl_data_device)),] )

motion = _rpythonic_function_(		"motion", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_device",		ctypes.POINTER(wl_data_device)),
	("time",		ctypes.c_uint32),
	("x",		ctypes.c_int32),
	("y",		ctypes.c_int32),] )

drop = _rpythonic_function_(		"drop", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_device",		ctypes.POINTER(wl_data_device)),] )

selection = _rpythonic_function_(		"selection", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_data_device",		ctypes.POINTER(wl_data_device)),
	("C_id",		ctypes.POINTER(wl_data_offer)),] )

ping = _rpythonic_function_(		"ping", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_shell_surface",		ctypes.POINTER(wl_shell_surface)),
	("serial",		ctypes.c_uint32),] )

configure = _rpythonic_function_(		"configure", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_shell_surface",		ctypes.POINTER(wl_shell_surface)),
	("edges",		ctypes.c_uint32),
	("width",		ctypes.c_int32),
	("height",		ctypes.c_int32),] )

popup_done = _rpythonic_function_(		"popup_done", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_shell_surface",		ctypes.POINTER(wl_shell_surface)),] )

capabilities = _rpythonic_function_(		"capabilities", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_seat",		ctypes.POINTER(wl_seat)),
	("capabilities",		ctypes.c_uint32),] )

button = _rpythonic_function_(		"button", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_pointer",		ctypes.POINTER(wl_pointer)),
	("serial",		ctypes.c_uint32),
	("time",		ctypes.c_uint32),
	("button",		ctypes.c_uint32),
	("state",		ctypes.c_uint32),] )

axis = _rpythonic_function_(		"axis", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_pointer",		ctypes.POINTER(wl_pointer)),
	("time",		ctypes.c_uint32),
	("axis",		ctypes.c_uint32),
	("value",		ctypes.c_int32),] )

keymap = _rpythonic_function_(		"keymap", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_keyboard",		ctypes.POINTER(wl_keyboard)),
	("format",		ctypes.c_uint32),
	("fd",		ctypes.c_int32),
	("size",		ctypes.c_uint32),] )

key = _rpythonic_function_(		"key", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_keyboard",		ctypes.POINTER(wl_keyboard)),
	("serial",		ctypes.c_uint32),
	("time",		ctypes.c_uint32),
	("key",		ctypes.c_uint32),
	("state",		ctypes.c_uint32),] )

modifiers = _rpythonic_function_(		"modifiers", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_keyboard",		ctypes.POINTER(wl_keyboard)),
	("serial",		ctypes.c_uint32),
	("mods_depressed",		ctypes.c_uint32),
	("mods_latched",		ctypes.c_uint32),
	("mods_locked",		ctypes.c_uint32),
	("group",		ctypes.c_uint32),] )

down = _rpythonic_function_(		"down", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_touch",		ctypes.POINTER(wl_touch)),
	("serial",		ctypes.c_uint32),
	("time",		ctypes.c_uint32),
	("surface",		ctypes.POINTER(wl_surface)),
	("C_id",		ctypes.c_int32),
	("x",		ctypes.c_int32),
	("y",		ctypes.c_int32),] )

up = _rpythonic_function_(		"up", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_touch",		ctypes.POINTER(wl_touch)),
	("serial",		ctypes.c_uint32),
	("time",		ctypes.c_uint32),
	("C_id",		ctypes.c_int32),] )

frame = _rpythonic_function_(		"frame", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_touch",		ctypes.POINTER(wl_touch)),] )

cancel = _rpythonic_function_(		"cancel", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_touch",		ctypes.POINTER(wl_touch)),] )

geometry = _rpythonic_function_(		"geometry", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_output",		ctypes.POINTER(wl_output)),
	("x",		ctypes.c_int32),
	("y",		ctypes.c_int32),
	("physical_width",		ctypes.c_int32),
	("physical_height",		ctypes.c_int32),
	("subpixel",		ctypes.c_int32),
	("make",		ctypes.POINTER(ctypes.c_char)),
	("model",		ctypes.POINTER(ctypes.c_char)),] )

mode = _rpythonic_function_(		"mode", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("wl_output",		ctypes.POINTER(wl_output)),
	("flags",		ctypes.c_uint32),
	("width",		ctypes.c_int32),
	("height",		ctypes.c_int32),
	("refresh",		ctypes.c_int32),] )

wl_display_update_func_t = _rpythonic_function_(		"wl_display_update_func_t", ctypes.c_int, [
	("mask",		ctypes.c_uint32),
	("data",		ctypes.POINTER(ctypes.c_void_p)),] )

wl_callback_func_t = _rpythonic_function_(		"wl_callback_func_t", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("time",		ctypes.c_uint32),] )

wl_display_connect = _rpythonic_function_(		"wl_display_connect", ctypes.POINTER(wl_display), [
	("name",		ctypes.POINTER(ctypes.c_char)),] )

wl_display_disconnect = _rpythonic_function_(		"wl_display_disconnect", ctypes.c_void_p, [
	("display",		ctypes.POINTER(wl_display)),] )

wl_display_get_fd = _rpythonic_function_(		"wl_display_get_fd", ctypes.c_int, [
	("display",		ctypes.POINTER(wl_display)),
	("update",		ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_uint32,ctypes.POINTER(ctypes.c_void_p),)),
	("data",		ctypes.POINTER(ctypes.c_void_p)),] )

wl_display_iterate = _rpythonic_function_(		"wl_display_iterate", ctypes.c_void_p, [
	("display",		ctypes.POINTER(wl_display)),
	("mask",		ctypes.c_uint32),] )

wl_display_flush = _rpythonic_function_(		"wl_display_flush", ctypes.c_void_p, [
	("display",		ctypes.POINTER(wl_display)),] )

wl_display_roundtrip = _rpythonic_function_(		"wl_display_roundtrip", ctypes.c_void_p, [
	("display",		ctypes.POINTER(wl_display)),] )

wl_display_global_func_t = _rpythonic_function_(		"wl_display_global_func_t", ctypes.c_void_p, [
	("display",		ctypes.POINTER(wl_display)),
	("C_id",		ctypes.c_uint32),
	("interface",		ctypes.POINTER(ctypes.c_char)),
	("version",		ctypes.c_uint32),
	("data",		ctypes.POINTER(ctypes.c_void_p)),] )

wl_display_remove_global_listener = _rpythonic_function_(		"wl_display_remove_global_listener", ctypes.c_void_p, [
	("display",		ctypes.POINTER(wl_display)),
	("listener",		ctypes.POINTER(wl_global_listener)),] )

wl_display_add_global_listener = _rpythonic_function_(		"wl_display_add_global_listener", ctypes.POINTER(wl_global_listener), [
	("display",		ctypes.POINTER(wl_display)),
	("handler",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(wl_display),ctypes.c_uint32,ctypes.POINTER(ctypes.c_char),ctypes.c_uint32,ctypes.POINTER(ctypes.c_void_p),)),
	("data",		ctypes.POINTER(ctypes.c_void_p)),] )

wl_display_get_global = _rpythonic_function_(		"wl_display_get_global", ctypes.c_uint32, [
	("display",		ctypes.POINTER(wl_display)),
	("interface",		ctypes.POINTER(ctypes.c_char)),
	("version",		ctypes.c_uint32),] )

wl_log_set_handler_client = _rpythonic_function_(		"wl_log_set_handler_client", ctypes.c_void_p, [
	("handler",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_char),ctypes.c_char,)),] )


_rpythonic_convert_structs_to_objects()

_rpythonic_setup_return_wrappers()
_rpythonic_make_nice_global_enums_()
_rpythonic_clean_up_missing_functions_()
_rpythonic_strip_prefixes_(['wl_', 'WL_'])