## generated by RPythonic 0.4.8g	| host: 64bits
## http://code.google.com/p/rpythonic/
import os, sys, ctypes, inspect
__os = os
__sys = sys
__inspect = inspect
_CTYPES_CDLLS = []	# support loading functions from multiple libraries


PYTHON_RESERVED_KEYWORDS = 'for while in as global with try except lambda return raise if else elif eval exec and not or break continue finally print yield del def class assert from is pass'.split()


IS32BIT = (ctypes.sizeof(ctypes.c_void_p)==4)

_ISPYTHON2 = sys.version_info[0] == 2
if _ISPYTHON2: _NULLBYTE = '\0'
else: _NULLBYTE = bytes( chr(0), 'ascii' )

def _CHARP2STRING( charp, encoding='utf-8' ):
	b = bytes()
	i = 0
	while True:
		char = charp[ i ]
		if char == _NULLBYTE: break
		else:
			b += char
			i += 1
	return b.decode( encoding )

## try to load precompiled c-libraries from this directory, if the library is not there try to load from the system.
_clibs_dir = os.path.dirname(os.path.abspath(__file__))

def _load_ctypes_lib( name ):
	if __os.name == 'posix':
		if __sys.platform.startswith('linux'):
			if not name.endswith('.so'): name += '.so'
			if not name.startswith('lib'): name = 'lib' + name

			if IS32BIT: 	path = __os.path.join(_clibs_dir,'linux32')
			else: 		path = __os.path.join(_clibs_dir,'linux64')
			url = __os.path.join( path, name )
			if __os.path.isfile( url ): return ctypes.CDLL(url)
			elif __os.path.isfile( '/usr/local/lib/%s'%name ): return ctypes.CDLL('/usr/local/lib/%s'%name)
			elif __os.path.isfile( '/usr/local/lib64/%s'%name ) and not IS32BIT: return ctypes.CDLL('/usr/local/lib64/%s'%name)
			elif __os.path.isfile( '/usr/lib/%s'%name ): return ctypes.CDLL('/usr/lib/%s'%name)
			elif __os.path.isfile( './%s'%name ): return ctypes.CDLL('./%s'%name)
			
			elif __os.path.isfile( '/usr/lib/%s.0'%name ):	# Fedora style
				return ctypes.CDLL('/usr/lib/%s.0'%name )
			elif __os.path.isfile( '/usr/lib64/%s.0'%name ):	# Fedora style
				return ctypes.CDLL('/usr/lib64/%s.0'%name )

			else:	# fallback
				print('[ falling back to loading from current process ]')
				try: return ctypes.CDLL(name)
				except: return ctypes.CDLL('')

		elif sys.platform == 'darwin':
			name += '.dylib'
			if IS32BIT: 	path = os.path.join(_clibs_dir,'osx32')
			else: 		path = os.path.join(_clibs_dir,'osx64')
			url = os.path.join( path, name )
			if os.path.isfile( url ): return ctypes.CDLL(url)
			else: return ctypes.CDLL(name) #fallback

	elif os.name == 'nt':
		name += '.dll'
		if IS32BIT: 	path = os.path.join(_clibs_dir,'win32')
		else: 		path = os.path.join(_clibs_dir,'win64')
		url = os.path.join( path, name )
		if os.path.isfile( url ): return ctypes.CDLL(url)
		else: return ctypes.CDLL(name) #fallback

RPYTHONIC_WRAPPER_FUNCTIONS = {}
RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES = []
RPYTHONIC_AUTOPREFIX_IGNORE = []

## ctypes does not clearly expose these types ##
PyCFuncPtrType = type(ctypes.CFUNCTYPE(ctypes.c_void_p))
PyCArrayType = type( ctypes.c_int * 2 )
PyCPointerType = type( ctypes.POINTER(ctypes.c_int) )
PyCStructType = type( ctypes.Structure )
CArgObject = type( ctypes.byref(ctypes.c_int()) )

class _rpythonic_meta_(object):
	'''
	Reserved Attributes:
		POINTER
		CSTRUCT
		CAST
	'''
	_rpythonic_ = True		# workaround for now, must have a way to know if object is a meta from another module, isinstance(o,_rpythonic_meta_) will fail in those cases. another workaround could be check sys.modules for other rpythonic modules and fetch _rpythonic_meta_ from there.
	def __init__(self, *args, **kw ):							# cheap trick, abuse **kw, and look for "pointer", "cast"
		if kw and 'pointer' not in kw: raise SyntaxError	# sorry, you can not init with keywords
		elif kw and 'pointer' in kw:
			if 'cast' in kw and kw['cast']:
				self.POINTER = ctypes.cast( kw['pointer'], ctypes.POINTER(self.CSTRUCT) )
			else: self.POINTER = kw['pointer']
		else: self.POINTER = ctypes.pointer( self.CSTRUCT(*args) )
		self.POINTER.pyobject = self	# .pyobject is local to this pointer "object"

	def __getattr__(self,name):
		if hasattr( self.POINTER.contents, name ):
			return getattr( self.POINTER.contents, name )

		else:	# when rpythonic failed to generate good bindings - these lookups should be cached
			for parent in self._rpythonic_parent_classes_:
				if hasattr( parent, name ):
					method = getattr( parent, name )	# should check if it really is an unbound method
					if method in parent._rpythonic_unbound_lookup_:
						func = parent._rpythonic_unbound_lookup_[ method ]
						n = func.name
						if len(func.argnames) > 1:
							argnames = func.argnames[ 1 : ]
							a = ',' + '=None,'.join( argnames ) + '=None'
							b = ','.join( argnames )
						else: a = b = ''
						lamb = eval( 'lambda self %s: %s( self.POINTER, %s )' %(a,n,b) )
						setattr( self.__class__, name, lamb )
						#return lamb	# this would return the unbound lambda, must call getattr again
						return getattr( self, name )
					else:
						# this can happen if self also inherits from the same parent class,
						# assume that by continuing this reaches that shared parent class,
						# and the lambda above is created as normal.
						continue
			## last resort, load from global name space ##
			G = globals()
			if name in G: return lambda *args: G[name](self.POINTER, *args)
			else:
				for prefix in self._autoprefix_:
					n = prefix + name
					if n in G: return lambda *args: G[n](self.POINTER, *args)
				print( 'possible auto-prefixes available', self._autoprefix_ )
				raise AttributeError

	def __call__(self, type=False):
		print('calling object is DEPRECATED - use ob.POINTER or ob.CSTRUCT')
		if type: return self.CSTRUCT
		else: return self.POINTER


def _rpythonic_generate_subclass_( name, struct, functions ):
	head = 'class %s( _rpythonic_meta_ ):' %name
	body = [ 
		'_rpythonic_parent_classes_ = []' ,
		'_rpythonic_unbound_lookup_ = {}' 
	]

	names = [ func.name for func in functions ]

	possibles = {}
	rank = []		# rank by longest name
	if len(names) > 3000: print('too many functions to use this hack')
	else:
		for n1 in names:
			prefix = ''
			for i,char in enumerate(n1):
				prefix += char
				if prefix not in possibles:
					possibles[ prefix ] = 0
					for n2 in names:
						if n2.startswith( prefix ):
							possibles[ prefix ] += 1

					if not rank or len(prefix) > len(rank[-1]) and possibles[prefix] > len(names)/4:
						rank.append( prefix )

	top = []
	while rank:
		best = rank.pop()
		if possibles[best] > len(functions)/2 and best not in names:
			if best.endswith('_set_') or best.endswith('_get_'): best = best[ : -4 ]
			elif best.endswith('Set') or best.endswith('Get'): best = best[ : -3 ]

			rem = []
			for other in rank:
				if best.startswith(other): rem.append( other )
			for r in rem: rank.remove( r )

			if best not in top: top.append( best )

		if len(top) > 3: break

	for n in names:		# find shortest prefixes #
		prefix = ''
		for i,char in enumerate(n):		# cammelCase
			if i==0: prefix += char; continue
			if char.isupper() and len(prefix) >= 2: break
			prefix += char
		if prefix and prefix != n and len(prefix) >= 2:
			hits = 0
			for other in names:
				if other.startswith( prefix ): hits += 1
			if hits >= 2 and prefix not in top:
				top.append( prefix )
				if len(top) >= 6: break

	## setup full names
	for func in functions:
		n = func.name
		if len(func.argnames) > 1:
			argnames = func.argnames[ 1 : ]
			a = ',' + '=None,'.join( argnames ) + '=None'
			b = ','.join( argnames )
		else: a = b = ''

		fhead = 'def %s( self %s ):' %(n,a)
		fbody = ['return %s(self.POINTER, %s)' %(func.name,b)]
		g = fhead + '\n\t\t' + '\n\t\t'.join( fbody )
		body.append( g )
		#body.append( '%s._rpythonic_function_ = %s' %(func.name, func.name) )

	## setup short names ##
	for n in names:
		for prefix in top:
			if n.startswith(prefix) and n[len(prefix):] not in names:
				alt = n[ len(prefix) : ]
				if alt and alt != n and alt not in PYTHON_RESERVED_KEYWORDS and not alt.isdigit() and not alt[0].isdigit():
					body.append( '%s = %s' %(alt,n) )
					names.append( alt )

	gen = head + '\n\t' + '\n\t'.join( body )
	try: exec( gen )
	except:
		print( gen )
		raise SyntaxError

	klass = locals()[name]
	klass.CSTRUCT = struct	# ctypes struct class

	klass._autoprefix_ = top
	for func in functions:
		unbound = getattr( klass, func.name )
		klass._rpythonic_unbound_lookup_[ unbound ] = func
		# klass.longname is klass.shortname = False
		# klass.longname == klass.shortname = True
	return klass

def _rpythonic_convert_structs_to_objects():
	G = globals()
	for klass in _OOAPI_:
		altname = name = klass.__name__
		prefix = ''
		for i,char in enumerate(name):
			if i==0: prefix += char; continue
			if char.isupper(): break
			prefix += char
		if prefix and prefix != name:
			hits = 0
			for other in _OOAPI_:
				if other is not klass:
					if other.__name__.startswith( prefix ): hits += 1
			if hits >= 2:
				altname = name[ len(prefix) : ]

		funcs = _OOAPI_[ klass ]
		newklass = _rpythonic_generate_subclass_( altname, klass, funcs )
		klass._rpythonic_wrapper_class_ = newklass
		G[ name ] = newklass	# replace struct with wrapper
		if altname not in G: G[ altname ] = newklass	# safely define with nicer name
		elif altname != name: # odd cases, maybe a function that returns the object, almost never happens.
			print('WARN - not replacing something with struct wrapper:', G[altname] )


def _rpythonic_setup_return_wrappers():
	R = _rpythonic_function_
	for klass in _OOAPI_:
		if klass in _OOAPI_RETURNS_OBJECT_:
			for f in _OOAPI_RETURNS_OBJECT_[klass]:
				f.object_oriented = True
				if not f.return_wrapper:	# just in case the ctypes footer had already defined it, do not overwrite
					f.return_wrapper = klass._rpythonic_wrapper_class_


###############################################################
##						OLD META FUNC						##
###############################################################
def _rpythonic_function_( name, result=ctypes.c_void_p, args=[]):
	mname = '_metafunc_%s' %name
	exec( 'class %s( _rpythonic_metafunc_ ): pass' %mname )
	k = locals()[mname]
	return k( name, result, args )
_OOAPI_ = {}
_OOAPI_RETURNS_OBJECT_ = {}
class _rpythonic_metafunc_(object):
	def __init__(self, name, result=ctypes.c_void_p, args=[]):
		self.name = name
		self.result = result
		self.argtypes = []		# can dynamically change CFUNCTYPE trick
		self.argnames = []
		self.argtypestypes = []
		for i,arg in enumerate(args):
			n,t = arg
			if n in PYTHON_RESERVED_KEYWORDS: n = 'C_'+n
			if n in self.argnames: n = '%s%s' %(n,i)
			self.argnames.append( n )
			self.argtypes.append( t )
			self.argtypestypes.append( type(t) )		# precomputed for speed

		self.argnames = tuple( self.argnames )				# should never change
		self.numargs = len( self.argtypes )
		self.callbacks = [None] * self.numargs
		self.return_wrapper = None
		self.object_oriented = False
		self.function = None
		for cdll in _CTYPES_CDLLS:	# functions could be multiple libraries
			if hasattr(cdll, self.name):
				func = self.function = getattr(cdll, self.name )
				RPYTHONIC_WRAPPER_FUNCTIONS[ name ] = self
				break
		if not self.function:
			RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES.append( name )

		if self.function: self.reset()

	def change_argument_type( self, name, t ):
		idx = self.argnames.index( name )
		self.argtypes[ idx ] = t
		self.argtypestypes[ idx ] = type(t)
		self.function.argtypes = self.argtypes

	def reset(self):
		if self.argnames:
			a = ',' + '=None,'.join( self.argnames ) + '=None'
			b = ','.join( self.argnames )
		else: a = b = ''

		callmeth = eval( 'lambda self %s: self._call_( %s )' %(a,b) )
		setattr( self.__class__, '__call__', callmeth )

		self.function.restype = self.result
		self.function.argtypes = self.argtypes

		if type( self.result ) is PyCPointerType and type(self.result._type_) is PyCStructType:
			klass = self.result._type_
			if klass not in _OOAPI_RETURNS_OBJECT_: _OOAPI_RETURNS_OBJECT_[klass] = []
			_OOAPI_RETURNS_OBJECT_[klass].append( self )

		self.defaults = []
		for i in range( self.numargs ):
			T = self.argtypes[ i ]
			if type(T) is PyCFuncPtrType:
				p = T()	# func pointers can not be None
				self.defaults.append( p )
				self.callbacks[ i ] = p					# save reference
			elif T in (ctypes.c_int, ctypes.c_uint, ctypes.c_long, ctypes.c_ulong):
				self.defaults.append( 0 )
			elif T in (ctypes.c_float, ctypes.c_double):
				self.defaults.append( .0 )
			else: self.defaults.append( None )	# None is allowed for all other types

			## generate OO API ##
			if i == 0 and type(T) is PyCPointerType and type(T._type_) is PyCStructType:
				klass = T._type_
				if klass not in _OOAPI_: _OOAPI_[ klass ] = []
				_OOAPI_[ klass ].append( self )

	def _call_( self, *args ):			# allow flexible calling types
		cargs = list( self.defaults )
		for i,arg in enumerate(args):
			if isinstance( arg, _rpythonic_meta_ ): arg = arg.POINTER
			elif hasattr( arg, '_rpythonic_' ): arg = arg.POINTER		# workaround - instance from another module

			t = type(arg)
			k = self.argtypes[ i ]
			kt = self.argtypestypes[ i ]
			if arg is None and cargs[i] is not None:	# use user defaults, very rare cases
				continue

			elif t is bool and k is ctypes.c_int:
				if arg: cargs[i] = 1	#ctypes.c_int(1)
				else: cargs[i] = 0	#ctypes.c_int(0)

			elif t in (list,tuple):				# convert lists and tuples into array
				if kt is PyCArrayType:
					cargs[ i ] = k(*arg)
				elif kt is PyCStructType:
					if k._array_wrapper_: cargs[ i ] = k(arg)	# allow easy array init
					else: cargs[ i ] = k(*arg)							# allow multiple args
				elif kt is PyCPointerType:
					cargs[ i ] = _convert_nested_list_to_pointer( k, arg )
				else: assert 0

			elif isinstance( arg, ctypes._Pointer ) and t is not k and kt is PyCPointerType:
				cargs[ i ] = ctypes.cast( arg, k )		# generic's that need to be cast

			elif kt is PyCStructType and isinstance( arg, ctypes._Pointer ):
				cargs[ i ] = arg.contents	# fixed may25

			elif kt is PyCPointerType and not isinstance( arg, (ctypes._Pointer,CArgObject) ):
				if t in (int,float,bool): ptr = k( k._type_(arg) )
				elif t is str:
					if not _ISPYTHON2: arg = arg.encode('utf-8')	# encode to ascii in python3
					ptr = ctypes.create_string_buffer(arg)				# correct and pypy compatible
				elif t in (PyCStructType, PyCArrayType):
					ptr = ctypes.cast( ctypes.pointer( arg ), k )
				else:
					ptr = arg	# TODO print warning?
				cargs[ i ] = ptr

			elif kt is PyCFuncPtrType:
				if t.__name__ == 'CFunctionType': cargs[ i ] = arg		# assume outside holds pointer
				else:													# this is not safe #
					cargs[ i ] = self.callbacks[ i ] = k( arg )				# assume arg is a callable
			else:
				cargs[ i ] = arg		# directly pass

		## if you define your own return_wrapper, it must take keyword "pointer"
		if self.return_wrapper: return self.return_wrapper( pointer=self.function( *cargs ) )
		else: return self.function( *cargs )



def _convert_nested_list_to_pointer( k, arg ):
	depth = 0; s = k
	while True:
		if type(s) is PyCPointerType:
			s = getattr( s, '_type_' )
			depth += 1
		else: break
	assert depth and depth <= 2
	if depth == 1:
		T = k._type_
		ptr = k( k._type_() )
		for i in range( len(arg) ):
			ptr[ i ] = T( *arg[i] )
	elif depth == 2:
		T = k._type_._type_
		_ptr = k._type_( k._type_._type_() )
		for i in range(len( arg )):
			for j in range( len(arg[i]) ):
				_ptr[ j ] = T( *arg[ i ][ j ] )
		ptr = k( _ptr )
	return ptr


def __freeze_rpythonic_struct( cls, fields ):
	if cls not in _OOAPI_: _OOAPI_[ cls ] = []	# wrap all structs
	try: setattr( cls, '_fields_', fields )
	except:
		print( 'WARN - bad order struct freeze', cls )
		#cls._fields_ = []

class _rpythonic_struct_( ctypes.Structure ):
	_array_wrapper_ = False
	_fields_ = []
	_methods_ = {}
	#def __call__(self): return self
	def __init__(self, *args, **kw ):
		cargs = []
		argtypes = []
		for a in self._fields_: argtypes.append( a[1] )
		if len(args) > len(argtypes): args = [args]	# allow both calling conventions
		for i,arg in enumerate( args ):
			if isinstance( arg, _rpythonic_meta_ ): arg = arg.POINTER

			t = type(arg)
			k = argtypes[ i ]
			if t in (list,tuple):
				if k.__class__.__name__	== 'PyCArrayType':
					cargs.append( k(*arg) )
				elif k.__class__.__name__ == 'PyCStructType':
					if k._array_wrapper_: cargs.append( k(arg) )	# allow easy array init
					else: cargs.append( k(*arg) )							# allow multiple args
			elif isinstance( arg, ctypes._Pointer ) and t is not k:
				cargs[ i ] = ctypes.cast( arg, k )	# generic's that need to be cast
			elif k.__class__.__name__ == 'PyCArrayType' and t in (float,int,bool):
				cargs.append( k(arg) )		# support init array from single value
			else:
				cargs.append( arg )		# directly pass

		ctypes.Structure.__init__(self, *cargs, **kw)


def _rpythonic_make_nice_global_enums_():
	G = globals()
	for name in RPYTHONIC_GLOBAL_ENUMS:
		if '_' in name and name.index('_') <= 4:
			altname = name[ name.index('_') + 1 : ]
			if altname not in G:
				G[altname] = RPYTHONIC_GLOBAL_ENUMS[ name ]

def _rpythonic_clean_up_missing_functions_():
	G = globals()
	for f in RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES:
		G.pop( f )
	print( "C functions loaded: %s" %len(RPYTHONIC_WRAPPER_FUNCTIONS) )
	print( "C functions failed: %s" %len(RPYTHONIC_WRAPPER_FUNCTIONS_FAILURES) )



###### NEW API #########
CTYPES_DLL = None

class _VOID_POINTER_CONTAINER_(object):
	def __init__(self, ptr, name=None):
		self._pointer_ = ptr
		self.name = name
NULL = _VOID_POINTER_CONTAINER_(None,'<null pointer>')


class meta:	# NEW API - allow run time switch from ctypes to rffi
	'''
	Methods:
		RPython will not allow object wrapper around a method (__call__ not allowed)
		keep C function names in list "__cfunctions__"
		rpythonic.enable_rffi( classA, classB )	
		can take advantage of methods in object-method-wrapper,
		generate rffi wrapper and set method on classA, etc.
		replaces object-method-wrapper with rffi-method

	Properties:
		CPython: obj.x=1
		RPython: obj.set_x(1)	
	'''
	METAS = []
	def __init__(self, constructors=[], methods={}, properties={}):
		#global CTYPES_DLL	# TODO update me to using _CTYPES_CDLLS
		#if not CTYPES_DLL:
		#	CTYPES_DLL = _load_ctypes_lib( _clib_name_ )

		self.constructors = constructors
		self.methods = methods
		self.properties = properties
		self.METAS.append( self )



	def __call__(self, cls ):
		print('@meta', cls )

		if not self.constructors:
			lamb = lambda s, _explicit_pointer_=None: setattr(s,'_pointer_',getattr(_explicit_pointer_,'_pointer_')) if hasattr(_explicit_pointer_,'_pointer_') else setattr(s,'_pointer_',_explicit_pointer_)
			lamb._debug = '(no constructor)'
			setattr( cls, '__init__', lamb )
		else:
			con = self._find_best_function( self.constructors )
			cfunc = self._build_cfunc( con )
			setattr( cls, '_%s'%con['name'], cfunc )
			g = self._gen_init( con )
			setattr( cls, '__init__', g )
		
		## set methods ##
		for name in self.methods:
			meth = self.methods[ name ]
			cfuncs = []
			for m in meth['functions']:
				cfunc = self._build_cfunc( m, method=True, static=meth['static'] )
				self._setup_return( cfunc, meth )
				setattr( cls, '_%s'%m['name'], cfunc )
				cfuncs.append( cfunc )

			f = self._find_best_function( meth['functions'] )
			g = self._gen_method( meth, f )
			g._cfuncs = cfuncs
			if meth['static']: g = classmethod( g )
			setattr( cls, name, g )

		for name in self.properties:
			print( 'property:', name )
			p = []
			for f in self.properties[name]:
				cfunc = self._build_cfunc( f )
				setattr( cls, '_%s'%f['name'], cfunc )
				g = self._gen_method( f, f )
				p.append( g )

			setattr( cls, name, property(*p) )

		return cls


	@staticmethod
	def _build_cfunc( info, method=False, static=False ):
		cfunc = getattr(CTYPES_DLL, info['name'])
		if method and not static: argtypes = [ ctypes.c_void_p ]
		else: argtypes = []
		for p in info['parameters']: argtypes.append( eval(p['ctypes_type']) )
		cfunc.argtypes = argtypes
		return cfunc

	@staticmethod
	def _setup_return( cfunc, info ):
		if not info['returns_fundamental']:
			cfunc.restype = ctypes.c_void_p
		elif info['returns_fundamental']:
			cfunc.restype = eval( info['returns_ctypes'] )
		else:
			cfunc.restype = ctypes.c_void_p

	@staticmethod
	def _gen_prepare_args( m ):
		a = []; b = []
		for i,p in enumerate(m['parameters']):
			if 'name' in p: n = p['name']
			else: n = '_unnamed_%s' %i
			if '<' in n: n = '_TODOfixme_%s' %i
			if n in PYTHON_RESERVED_KEYWORDS: n += str(i)
			if p['fundamental']:
				b.append( n )
				s = p['raw_type'].split()
				if 'default' in p:
					d = p['default']
					if p['raw_type'] in ('float', 'double'):
						if d.endswith('f'): d = d[:-1]
						d = d.replace(' ', '.')
						if 'e' in d: d = 0.0
						try: d = float(d)
						except: d = 0.0
					elif ('int' in s or 'size_t' in s) and not d.isdigit(): d = 0
					elif 'char' in s and '"' not in d: d = '""'
					elif d.lower() == 'false': d = False
					elif d.lower() == 'true': d = True
				elif 'char' in s: d = '""'
				elif 'float' in s or 'double' in s: d = 0.0
				elif 'size_t' in s or 'int' in s or 'long' in s or 'short' in s: d = 0
				elif p['raw_type'] == 'bool': d = False
				elif p['raw_type'] in ('void', '(template)'): d = 'NULL'
				else: print( p )
				a.append( n+'=%s' %d )

			else:
				b.append( '%s._pointer_'%n )
				a.append( n+'=NULL' )
		return a, b

	@staticmethod
	def _gen_init( m ):
		a, b = meta._gen_prepare_args( m )
		if a: e = 'lambda _py_self_, %s, _explicit_pointer_=None: ' %(','.join(a))
		else: e = 'lambda _py_self_, _explicit_pointer_=None: '
		e += 'setattr(_py_self_, "_pointer_", _py_self_._%s(%s))' %( m['name'], ','.join(b) )
		e += ' if not _explicit_pointer_ else '
		e += 'setattr(_py_self_, "_pointer_", _explicit_pointer_)'
		print( e )
		lamb = eval( e ); lamb._debug = e; lamb._introspect = m
		return lamb

	@staticmethod
	def _find_best_function( funcs ):
		best = funcs[0]
		score = -1
		if len(funcs) > 1:
			for f in funcs:
				hits = 0
				for p in f['parameters']:
					if p['fundamental']: hits += 1
				if hits and hits == len( f['parameters'] ):
					if hits > score:
						score = hits
						best = f
		return best

	@staticmethod
	def _gen_method( m, f ):
		a, b = meta._gen_prepare_args( f )
		if a: e = 'lambda _py_self_, %s: ' %(','.join(a))
		else: e = 'lambda _py_self_: '

		if 'static' in m and m['static']:	# static in c++ is like a classmethod
			c = '_py_self_._%s( %s )' %( f['name'], ','.join(b) )
		else:
			c = '_py_self_._%s( _py_self_._pointer_, %s )' %( f['name'], ','.join(b) )

		if not m['returns_fundamental']:
			if 'returns_unknown' in m or '<' in m['returns']: c = '_VOID_POINTER_CONTAINER_( %s, name="%s" )' %(c,m['returns'])
			else:
				something = m['returns'].replace('::', '.')
				c = '%s( _explicit_pointer_=%s )' %(something, c)

		e += c; lamb = eval( e )
		lamb._debug = e; lamb._introspect = f
		return lamb


	META_FUNCTIONS = []
	@classmethod
	def function( self, info ):
		print('@meta.function', info['name'] )
		#global CTYPES_DLL
		#if not CTYPES_DLL:
		#	CTYPES_DLL = _load_ctypes_lib( _clib_name_ )

		cfunc = self._build_cfunc( info, method=False, static=True )
		setattr( meta, '_%s'%info['name'], cfunc )
		self._setup_return( cfunc, info )
		a, b = meta._gen_prepare_args( info )
		e = 'lambda %s: ' %(','.join(a))
		c = 'meta._%s( %s )' %( info['name'], ','.join(b) )

		if not info['returns_fundamental']:
			if 'returns_unknown' in info or '<' in info['returns']:
				c = '_VOID_POINTER_CONTAINER_( %s, name="%s" )' %(c,info['returns'])
			else:
				something = info['returns'].replace('::', '.')
				c = '%s( _explicit_pointer_=%s )' %(something, c)
		e += c
		lamb = eval( e )
		lamb._debug = e
		lamb._introspect = info
		return lamb



def _rpythonic_strip_prefixes_( prefixes ):
	G = globals()
	names = list(G.keys())	# ensure list in py3
	for name in names:
		for prefix in prefixes:
			if name.startswith( prefix ):
				newname = name[ len(prefix) : ]
				if newname and newname not in G:
					G[ newname ] = G[ name ]


########################################################
##				Load Dynamic Libaries					##
def _rpythonic_load_dynamic_libraries(names):
	global _CTYPES_CDLLS
	for name in names:
		cdll = _load_ctypes_lib( name )
		if cdll:
			print('[[dynamic library loaded: %s]]' %name)
			_CTYPES_CDLLS.append( cdll )
#----------------------------------------------------------#
print( os.path.abspath( os.path.curdir ) )



_rpythonic_load_dynamic_libraries( ['libcares'] )

## macro globals ##
ARES_SUCCESS = 0
ARES_ENODATA = 1
ARES_EFORMERR = 2
ARES_ESERVFAIL = 3
ARES_ENOTFOUND = 4
ARES_ENOTIMP = 5
ARES_EREFUSED = 6
ARES_EBADQUERY = 7
ARES_EBADNAME = 8
ARES_EBADFAMILY = 9
ARES_EBADRESP = 10
ARES_ECONNREFUSED = 11
ARES_ETIMEOUT = 12
ARES_EOF = 13
ARES_EFILE = 14
ARES_ENOMEM = 15
ARES_EDESTRUCTION = 16
ARES_EBADSTR = 17
ARES_EBADFLAGS = 18
ARES_ENONAME = 19
ARES_EBADHINTS = 20
ARES_ENOTINITIALIZED = 21
ARES_ELOADIPHLPAPI = 22
ARES_EADDRGETNETWORKPARAMS = 23
ARES_ECANCELLED = 24
ARES_FLAG_USEVC = 1
ARES_FLAG_PRIMARY = 2
ARES_FLAG_IGNTC = 4
ARES_FLAG_NORECURSE = 8
ARES_FLAG_STAYOPEN = 16
ARES_FLAG_NOSEARCH = 32
ARES_FLAG_NOALIASES = 64
ARES_FLAG_NOCHECKRESP = 128
ARES_OPT_FLAGS = 1
ARES_OPT_TIMEOUT = 2
ARES_OPT_TRIES = 4
ARES_OPT_NDOTS = 8
ARES_OPT_UDP_PORT = 16
ARES_OPT_TCP_PORT = 32
ARES_OPT_SERVERS = 64
ARES_OPT_DOMAINS = 128
ARES_OPT_LOOKUPS = 256
ARES_OPT_SOCK_STATE_CB = 512
ARES_OPT_SORTLIST = 1024
ARES_OPT_SOCK_SNDBUF = 2048
ARES_OPT_SOCK_RCVBUF = 4096
ARES_OPT_TIMEOUTMS = 8192
ARES_OPT_ROTATE = 16384
ARES_NI_NOFQDN = 1
ARES_NI_NUMERICHOST = 2
ARES_NI_NAMEREQD = 4
ARES_NI_NUMERICSERV = 8
ARES_NI_DGRAM = 16
ARES_NI_TCP = 0
ARES_NI_UDP = 16
ARES_NI_SCTP = 32
ARES_NI_DCCP = 64
ARES_NI_NUMERICSCOPE = 128
ARES_NI_LOOKUPHOST = 256
ARES_NI_LOOKUPSERVICE = 512
ARES_NI_IDN = 1024
ARES_NI_IDN_ALLOW_UNASSIGNED = 2048
ARES_NI_IDN_USE_STD3_ASCII_RULES = 4096
ARES_AI_CANONNAME = 1
ARES_AI_NUMERICHOST = 2
ARES_AI_PASSIVE = 4
ARES_AI_NUMERICSERV = 8
ARES_AI_V4MAPPED = 16
ARES_AI_ALL = 32
ARES_AI_ADDRCONFIG = 64
ARES_AI_IDN = 1024
ARES_AI_IDN_ALLOW_UNASSIGNED = 2048
ARES_AI_IDN_USE_STD3_ASCII_RULES = 4096
ARES_AI_CANONIDN = 8192
ARES_GETSOCK_MAXNUM = 16
ARES_LIB_INIT_NONE = 0
ARES_LIB_INIT_WIN32 = 1
ARES_LIB_INIT_ALL = 1
ARES_SOCKET_BAD = -1
## enums ##
SHUT_RD = 0 
SHUT_WR = 1 
SHUT_RDWR = 2 

_socket_type = { 
	"SOCK_STREAM" : 1, 
	"SOCK_DGRAM" : 2, 
	"SOCK_RAW" : 3, 
	"SOCK_RDM" : 4, 
	"SOCK_SEQPACKET" : 5, 
	"SOCK_DCCP" : 6, 
	"SOCK_PACKET" : 10, 
	"SOCK_CLOEXEC" : 2000000, 
	"SOCK_NONBLOCK" : 4000, 
}

MSG_OOB = 1 
MSG_PEEK = 2 
MSG_DONTROUTE = 4 
MSG_CTRUNC = 8 
MSG_PROXY = 16 
MSG_TRUNC = 32 
MSG_DONTWAIT = 64 
MSG_EOR = 128 
MSG_WAITALL = 256 
MSG_FIN = 512 
MSG_SYN = 1024 
MSG_CONFIRM = 2048 
MSG_RST = 4096 
MSG_ERRQUEUE = 8192 
MSG_NOSIGNAL = 16384 
MSG_MORE = 32768 
MSG_WAITFORONE = 65536 
MSG_CMSG_CLOEXEC = 1073741824 

SCM_RIGHTS = 1 

IPPROTO_IP = 0 
IPPROTO_HOPOPTS = 0 
IPPROTO_ICMP = 1 
IPPROTO_IGMP = 2 
IPPROTO_IPIP = 4 
IPPROTO_TCP = 6 
IPPROTO_EGP = 8 
IPPROTO_PUP = 12 
IPPROTO_UDP = 17 
IPPROTO_IDP = 22 
IPPROTO_TP = 29 
IPPROTO_DCCP = 33 
IPPROTO_IPV6 = 41 
IPPROTO_ROUTING = 43 
IPPROTO_FRAGMENT = 44 
IPPROTO_RSVP = 46 
IPPROTO_GRE = 47 
IPPROTO_ESP = 50 
IPPROTO_AH = 51 
IPPROTO_ICMPV6 = 58 
IPPROTO_NONE = 59 
IPPROTO_DSTOPTS = 60 
IPPROTO_MTP = 92 
IPPROTO_ENCAP = 98 
IPPROTO_PIM = 103 
IPPROTO_COMP = 108 
IPPROTO_SCTP = 132 
IPPROTO_UDPLITE = 136 
IPPROTO_RAW = 255 
IPPROTO_MAX = 256 

IPPORT_ECHO = 7 
IPPORT_DISCARD = 9 
IPPORT_SYSTAT = 11 
IPPORT_DAYTIME = 13 
IPPORT_NETSTAT = 15 
IPPORT_FTP = 21 
IPPORT_TELNET = 23 
IPPORT_SMTP = 25 
IPPORT_TIMESERVER = 37 
IPPORT_NAMESERVER = 42 
IPPORT_WHOIS = 43 
IPPORT_MTP = 57 
IPPORT_TFTP = 69 
IPPORT_RJE = 77 
IPPORT_FINGER = 79 
IPPORT_TTYLINK = 87 
IPPORT_SUPDUP = 95 
IPPORT_EXECSERVER = 512 
IPPORT_LOGINSERVER = 513 
IPPORT_CMDSERVER = 514 
IPPORT_EFSSERVER = 520 
IPPORT_BIFFUDP = 512 
IPPORT_WHOSERVER = 513 
IPPORT_ROUTESERVER = 520 
IPPORT_RESERVED = 1024 
IPPORT_USERRESERVED = 5000 

## simple enums ##
RPYTHONIC_GLOBAL_ENUMS = { 
 "SHUT_RD" : 0,  "SHUT_WR" : 1,  "SHUT_RDWR" : 2, 
 "MSG_OOB" : 1,  "MSG_PEEK" : 2,  "MSG_DONTROUTE" : 4,  "MSG_CTRUNC" : 8,  "MSG_PROXY" : 16,  "MSG_TRUNC" : 32,  "MSG_DONTWAIT" : 64,  "MSG_EOR" : 128,  "MSG_WAITALL" : 256,  "MSG_FIN" : 512,  "MSG_SYN" : 1024,  "MSG_CONFIRM" : 2048,  "MSG_RST" : 4096,  "MSG_ERRQUEUE" : 8192,  "MSG_NOSIGNAL" : 16384,  "MSG_MORE" : 32768,  "MSG_WAITFORONE" : 65536,  "MSG_CMSG_CLOEXEC" : 1073741824, 
 "SCM_RIGHTS" : 1, 
 "IPPROTO_IP" : 0,  "IPPROTO_HOPOPTS" : 0,  "IPPROTO_ICMP" : 1,  "IPPROTO_IGMP" : 2,  "IPPROTO_IPIP" : 4,  "IPPROTO_TCP" : 6,  "IPPROTO_EGP" : 8,  "IPPROTO_PUP" : 12,  "IPPROTO_UDP" : 17,  "IPPROTO_IDP" : 22,  "IPPROTO_TP" : 29,  "IPPROTO_DCCP" : 33,  "IPPROTO_IPV6" : 41,  "IPPROTO_ROUTING" : 43,  "IPPROTO_FRAGMENT" : 44,  "IPPROTO_RSVP" : 46,  "IPPROTO_GRE" : 47,  "IPPROTO_ESP" : 50,  "IPPROTO_AH" : 51,  "IPPROTO_ICMPV6" : 58,  "IPPROTO_NONE" : 59,  "IPPROTO_DSTOPTS" : 60,  "IPPROTO_MTP" : 92,  "IPPROTO_ENCAP" : 98,  "IPPROTO_PIM" : 103,  "IPPROTO_COMP" : 108,  "IPPROTO_SCTP" : 132,  "IPPROTO_UDPLITE" : 136,  "IPPROTO_RAW" : 255,  "IPPROTO_MAX" : 256, 
 "IPPORT_ECHO" : 7,  "IPPORT_DISCARD" : 9,  "IPPORT_SYSTAT" : 11,  "IPPORT_DAYTIME" : 13,  "IPPORT_NETSTAT" : 15,  "IPPORT_FTP" : 21,  "IPPORT_TELNET" : 23,  "IPPORT_SMTP" : 25,  "IPPORT_TIMESERVER" : 37,  "IPPORT_NAMESERVER" : 42,  "IPPORT_WHOIS" : 43,  "IPPORT_MTP" : 57,  "IPPORT_TFTP" : 69,  "IPPORT_RJE" : 77,  "IPPORT_FINGER" : 79,  "IPPORT_TTYLINK" : 87,  "IPPORT_SUPDUP" : 95,  "IPPORT_EXECSERVER" : 512,  "IPPORT_LOGINSERVER" : 513,  "IPPORT_CMDSERVER" : 514,  "IPPORT_EFSSERVER" : 520,  "IPPORT_BIFFUDP" : 512,  "IPPORT_WHOSERVER" : 513,  "IPPORT_ROUTESERVER" : 520,  "IPPORT_RESERVED" : 1024,  "IPPORT_USERRESERVED" : 5000, 

}
class __fsid_t(_rpythonic_struct_): _array_wrapper_ = True
class __sigset_t(_rpythonic_struct_): _array_wrapper_ = True
class timespec(_rpythonic_struct_): pass
class timeval(_rpythonic_struct_): pass
class fd_set(_rpythonic_struct_): _array_wrapper_ = True
class pthread_attr_t(ctypes.Union): pass
class __pthread_internal_list(_rpythonic_struct_): pass
class pthread_mutex_t(ctypes.Union): pass
class __pthread_mutex_s(_rpythonic_struct_): pass
class pthread_mutexattr_t(ctypes.Union): pass
class pthread_cond_t(ctypes.Union): pass
class pthread_condattr_t(ctypes.Union): pass
class pthread_rwlock_t(ctypes.Union): pass
class __data(_rpythonic_struct_): pass
class pthread_rwlockattr_t(ctypes.Union): pass
class pthread_barrier_t(ctypes.Union): pass
class pthread_barrierattr_t(ctypes.Union): pass
class iovec(_rpythonic_struct_): pass
class sockaddr(_rpythonic_struct_): _array_wrapper_ = True
class sockaddr_storage(_rpythonic_struct_): _array_wrapper_ = True
class msghdr(_rpythonic_struct_): pass
class cmsghdr(_rpythonic_struct_): _array_wrapper_ = True
class linger(_rpythonic_struct_): pass
class mmsghdr(_rpythonic_struct_): pass
class osockaddr(_rpythonic_struct_): _array_wrapper_ = True
class in_addr(_rpythonic_struct_): pass
class in6_addr(_rpythonic_struct_): pass
class __in6_u(ctypes.Union): pass
class sockaddr_in(_rpythonic_struct_): _array_wrapper_ = True
class sockaddr_in6(_rpythonic_struct_): pass
class ip_mreq(_rpythonic_struct_): pass
class ip_mreq_source(_rpythonic_struct_): pass
class ipv6_mreq(_rpythonic_struct_): pass
class group_req(_rpythonic_struct_): pass
class group_source_req(_rpythonic_struct_): pass
class ip_msfilter(_rpythonic_struct_): _array_wrapper_ = True
class group_filter(_rpythonic_struct_): _array_wrapper_ = True
class ip_opts(_rpythonic_struct_): _array_wrapper_ = True
class ip_mreqn(_rpythonic_struct_): pass
class in_pktinfo(_rpythonic_struct_): pass
class apattern(_rpythonic_struct_): pass
class ares_options(_rpythonic_struct_): pass
class hostent(_rpythonic_struct_): pass
class ares_channeldata(_rpythonic_struct_): pass
class ares_in6_addr(_rpythonic_struct_): pass
class _S6_un(ctypes.Union): pass
class ares_addrttl(_rpythonic_struct_): pass
class ares_addr6ttl(_rpythonic_struct_): pass
class ares_srv_reply(_rpythonic_struct_): pass
class ares_mx_reply(_rpythonic_struct_): pass
class ares_txt_reply(_rpythonic_struct_): pass
class ares_naptr_reply(_rpythonic_struct_): pass
class ares_soa_reply(_rpythonic_struct_): pass
class ares_addr_node(_rpythonic_struct_): pass
class addr(ctypes.Union): pass
## union and structures ##
__freeze_rpythonic_struct( __fsid_t, [
	( "__val", ( ctypes.c_int * 2 ) ),
])

__freeze_rpythonic_struct( __sigset_t, [
	( "__val", ctypes.c_uint64 ),
])

__freeze_rpythonic_struct( timespec, [
	( "tv_sec", ctypes.c_int64 ),
	( "tv_nsec", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( timeval, [
	( "tv_sec", ctypes.c_int64 ),
	( "tv_usec", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( fd_set, [
	( "__fds_bits", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( pthread_attr_t, [
	( "__size", ( ctypes.c_char * 56 ) ),
	( "__align", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( __pthread_internal_list, [
	( "__prev", ctypes.POINTER(__pthread_internal_list) ),
	( "__next", ctypes.POINTER(__pthread_internal_list) ),
])

__freeze_rpythonic_struct( __pthread_mutex_s, [
	( "__lock", ctypes.c_int ),
	( "__count", ctypes.c_uint ),
	( "__owner", ctypes.c_int ),
	( "__nusers", ctypes.c_uint ),
	( "__kind", ctypes.c_int ),
	( "__spins", ctypes.c_int ),
	( "__list", __pthread_internal_list ),
])

__freeze_rpythonic_struct( pthread_mutex_t, [
	( "__data", __pthread_mutex_s ),
	( "__size", ( ctypes.c_char * 40 ) ),
	( "__align", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( pthread_mutexattr_t, [
	( "__size", ( ctypes.c_char * 4 ) ),
	( "__align", ctypes.c_int ),
])

__freeze_rpythonic_struct( __data, [
	( "__lock", ctypes.c_int ),
	( "__nr_readers", ctypes.c_uint ),
	( "__readers_wakeup", ctypes.c_uint ),
	( "__writer_wakeup", ctypes.c_uint ),
	( "__nr_readers_queued", ctypes.c_uint ),
	( "__nr_writers_queued", ctypes.c_uint ),
	( "__writer", ctypes.c_int ),
	( "__shared", ctypes.c_int ),
	( "__pad1", ctypes.c_uint64 ),
	( "__pad2", ctypes.c_uint64 ),
	( "__flags", ctypes.c_uint ),
])

__freeze_rpythonic_struct( pthread_cond_t, [
	( "__data", __data ),
	( "__size", ( ctypes.c_char * 48 ) ),
	( "__align", ctypes.c_longlong ),
])

__freeze_rpythonic_struct( pthread_condattr_t, [
	( "__size", ( ctypes.c_char * 4 ) ),
	( "__align", ctypes.c_int ),
])

__freeze_rpythonic_struct( pthread_rwlock_t, [
	( "__data", __data ),
	( "__size", ( ctypes.c_char * 56 ) ),
	( "__align", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( pthread_rwlockattr_t, [
	( "__size", ( ctypes.c_char * 8 ) ),
	( "__align", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( pthread_barrier_t, [
	( "__size", ( ctypes.c_char * 32 ) ),
	( "__align", ctypes.c_int64 ),
])

__freeze_rpythonic_struct( pthread_barrierattr_t, [
	( "__size", ( ctypes.c_char * 4 ) ),
	( "__align", ctypes.c_int ),
])

__freeze_rpythonic_struct( iovec, [
	( "iov_base", ctypes.POINTER(ctypes.c_void_p) ),
	( "iov_len", ctypes.c_uint64 ),
])

__freeze_rpythonic_struct( sockaddr, [
	( "sa_family", ctypes.c_uint16 ),
	( "sa_data", ( ctypes.c_char * 14 ) ),
])

__freeze_rpythonic_struct( sockaddr_storage, [
	( "ss_family", ctypes.c_uint16 ),
	( "__ss_align", ctypes.c_uint64 ),
	( "__ss_padding", ctypes.c_char ),
])

__freeze_rpythonic_struct( msghdr, [
	( "msg_name", ctypes.POINTER(ctypes.c_void_p) ),
	( "msg_namelen", ctypes.c_uint ),
	( "msg_iov", ctypes.POINTER(iovec) ),
	( "msg_iovlen", ctypes.c_uint64 ),
	( "msg_control", ctypes.POINTER(ctypes.c_void_p) ),
	( "msg_controllen", ctypes.c_uint64 ),
	( "msg_flags", ctypes.c_int ),
])

__freeze_rpythonic_struct( cmsghdr, [
	( "cmsg_len", ctypes.c_uint64 ),
	( "cmsg_level", ctypes.c_int ),
	( "cmsg_type", ctypes.c_int ),
	( "__cmsg_data", ctypes.c_ubyte ),
])

__freeze_rpythonic_struct( linger, [
	( "l_onoff", ctypes.c_int ),
	( "l_linger", ctypes.c_int ),
])

__freeze_rpythonic_struct( mmsghdr, [
])

__freeze_rpythonic_struct( osockaddr, [
	( "sa_family", ctypes.c_uint16 ),
	( "sa_data", ( ctypes.c_ubyte * 14 ) ),
])

__freeze_rpythonic_struct( in_addr, [
	( "s_addr", ctypes.c_uint32 ),
])

__freeze_rpythonic_struct( __in6_u, [
	( "__u6_addr8", ( ctypes.c_uint8 * 16 ) ),
	( "__u6_addr16", ( ctypes.c_uint16 * 8 ) ),
	( "__u6_addr32", ( ctypes.c_uint32 * 4 ) ),
])

__freeze_rpythonic_struct( in6_addr, [
	( "__in6_u", __in6_u ),
])

__freeze_rpythonic_struct( sockaddr_in, [
	( "sin_family", ctypes.c_uint16 ),
	( "sin_port", ctypes.c_uint16 ),
	( "sin_addr", in_addr ),
	( "sin_zero", ctypes.c_ubyte ),
])

__freeze_rpythonic_struct( sockaddr_in6, [
	( "sin6_family", ctypes.c_uint16 ),
	( "sin6_port", ctypes.c_uint16 ),
	( "sin6_flowinfo", ctypes.c_uint32 ),
	( "sin6_addr", in6_addr ),
	( "sin6_scope_id", ctypes.c_uint32 ),
])

__freeze_rpythonic_struct( ip_mreq, [
	( "imr_multiaddr", in_addr ),
	( "imr_interface", in_addr ),
])

__freeze_rpythonic_struct( ip_mreq_source, [
	( "imr_multiaddr", in_addr ),
	( "imr_interface", in_addr ),
	( "imr_sourceaddr", in_addr ),
])

__freeze_rpythonic_struct( ipv6_mreq, [
	( "ipv6mr_multiaddr", in6_addr ),
	( "ipv6mr_interface", ctypes.c_uint ),
])

__freeze_rpythonic_struct( group_req, [
	( "gr_interface", ctypes.c_uint32 ),
	( "gr_group", sockaddr_storage ),
])

__freeze_rpythonic_struct( group_source_req, [
	( "gsr_interface", ctypes.c_uint32 ),
	( "gsr_group", sockaddr_storage ),
	( "gsr_source", sockaddr_storage ),
])

__freeze_rpythonic_struct( ip_msfilter, [
	( "imsf_multiaddr", in_addr ),
	( "imsf_interface", in_addr ),
	( "imsf_fmode", ctypes.c_uint32 ),
	( "imsf_numsrc", ctypes.c_uint32 ),
	( "imsf_slist", ( in_addr * 1 ) ),
])

__freeze_rpythonic_struct( group_filter, [
	( "gf_interface", ctypes.c_uint32 ),
	( "gf_group", sockaddr_storage ),
	( "gf_fmode", ctypes.c_uint32 ),
	( "gf_numsrc", ctypes.c_uint32 ),
	( "gf_slist", ( sockaddr_storage * 1 ) ),
])

__freeze_rpythonic_struct( ip_opts, [
	( "ip_dst", in_addr ),
	( "ip_opts", ( ctypes.c_char * 40 ) ),
])

__freeze_rpythonic_struct( ip_mreqn, [
	( "imr_multiaddr", in_addr ),
	( "imr_address", in_addr ),
	( "imr_ifindex", ctypes.c_int ),
])

__freeze_rpythonic_struct( in_pktinfo, [
	( "ipi_ifindex", ctypes.c_int ),
	( "ipi_spec_dst", in_addr ),
	( "ipi_addr", in_addr ),
])

__freeze_rpythonic_struct( apattern, [
])

__freeze_rpythonic_struct( ares_options, [
	( "flags", ctypes.c_int ),
	( "timeout", ctypes.c_int ),
	( "tries", ctypes.c_int ),
	( "ndots", ctypes.c_int ),
	( "udp_port", ctypes.c_ushort ),
	( "tcp_port", ctypes.c_ushort ),
	( "socket_send_buffer_size", ctypes.c_int ),
	( "socket_receive_buffer_size", ctypes.c_int ),
	( "servers", ctypes.POINTER(in_addr) ),
	( "nservers", ctypes.c_int ),
	( "domains", ctypes.POINTER(ctypes.POINTER(ctypes.c_char)) ),
	( "ndomains", ctypes.c_int ),
	( "lookups", ctypes.POINTER(ctypes.c_char) ),
	( "sock_state_cb", ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.c_int,) ),
	( "sock_state_cb_data", ctypes.POINTER(ctypes.c_void_p) ),
	( "sortlist", ctypes.POINTER(apattern) ),
	( "nsort", ctypes.c_int ),
])

__freeze_rpythonic_struct( hostent, [
])

__freeze_rpythonic_struct( ares_channeldata, [
])

__freeze_rpythonic_struct( _S6_un, [
	( "_S6_u8", ( ctypes.c_ubyte * 16 ) ),
])

__freeze_rpythonic_struct( ares_in6_addr, [
	( "_S6_un", _S6_un ),
])

__freeze_rpythonic_struct( ares_addrttl, [
	( "ipaddr", in_addr ),
	( "ttl", ctypes.c_int ),
])

__freeze_rpythonic_struct( ares_addr6ttl, [
	( "ip6addr", ares_in6_addr ),
	( "ttl", ctypes.c_int ),
])

__freeze_rpythonic_struct( ares_srv_reply, [
	( "next", ctypes.POINTER(ares_srv_reply) ),
	( "host", ctypes.POINTER(ctypes.c_char) ),
	( "priority", ctypes.c_ushort ),
	( "weight", ctypes.c_ushort ),
	( "port", ctypes.c_ushort ),
])

__freeze_rpythonic_struct( ares_mx_reply, [
	( "next", ctypes.POINTER(ares_mx_reply) ),
	( "host", ctypes.POINTER(ctypes.c_char) ),
	( "priority", ctypes.c_ushort ),
])

__freeze_rpythonic_struct( ares_txt_reply, [
	( "next", ctypes.POINTER(ares_txt_reply) ),
	( "txt", ctypes.POINTER(ctypes.c_ubyte) ),
	( "length", ctypes.c_uint64 ),
])

__freeze_rpythonic_struct( ares_naptr_reply, [
	( "next", ctypes.POINTER(ares_naptr_reply) ),
	( "flags", ctypes.POINTER(ctypes.c_ubyte) ),
	( "service", ctypes.POINTER(ctypes.c_ubyte) ),
	( "regexp", ctypes.POINTER(ctypes.c_ubyte) ),
	( "replacement", ctypes.POINTER(ctypes.c_char) ),
	( "order", ctypes.c_ushort ),
	( "preference", ctypes.c_ushort ),
])

__freeze_rpythonic_struct( ares_soa_reply, [
	( "nsname", ctypes.POINTER(ctypes.c_char) ),
	( "hostmaster", ctypes.POINTER(ctypes.c_char) ),
	( "serial", ctypes.c_uint ),
	( "refresh", ctypes.c_uint ),
	( "retry", ctypes.c_uint ),
	( "expire", ctypes.c_uint ),
	( "minttl", ctypes.c_uint ),
])

__freeze_rpythonic_struct( addr, [
	( "addr4", in_addr ),
	( "addr6", ares_in6_addr ),
])

__freeze_rpythonic_struct( ares_addr_node, [
	( "next", ctypes.POINTER(ares_addr_node) ),
	( "family", ctypes.c_int ),
	( "addr", addr ),
])

## wrapper functions ##
ares_fds = _rpythonic_function_(		"ares_fds", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("read_fds",		ctypes.POINTER(fd_set)),
	("write_fds",		ctypes.POINTER(fd_set)),] )

ares_getsock = _rpythonic_function_(		"ares_getsock", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("socks",		ctypes.POINTER(ctypes.c_int)),
	("numsocks",		ctypes.c_int),] )

ares_timeout = _rpythonic_function_(		"ares_timeout", ctypes.POINTER(timeval), [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("maxtv",		ctypes.POINTER(timeval)),
	("tv",		ctypes.POINTER(timeval)),] )

ares_expand_name = _rpythonic_function_(		"ares_expand_name", ctypes.c_int, [
	("encoded",		ctypes.POINTER(ctypes.c_ubyte)),
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("s",		ctypes.POINTER(ctypes.POINTER(ctypes.c_char))),
	("enclen",		ctypes.POINTER(ctypes.c_long)),] )

ares_expand_string = _rpythonic_function_(		"ares_expand_string", ctypes.c_int, [
	("encoded",		ctypes.POINTER(ctypes.c_ubyte)),
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("s",		ctypes.POINTER(ctypes.POINTER(ctypes.c_ubyte))),
	("enclen",		ctypes.POINTER(ctypes.c_long)),] )

ares_parse_ns_reply = _rpythonic_function_(		"ares_parse_ns_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("host",		ctypes.POINTER(ctypes.POINTER(hostent))),] )

ares_parse_srv_reply = _rpythonic_function_(		"ares_parse_srv_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("srv_out",		ctypes.POINTER(ctypes.POINTER(ares_srv_reply))),] )

ares_parse_mx_reply = _rpythonic_function_(		"ares_parse_mx_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("mx_out",		ctypes.POINTER(ctypes.POINTER(ares_mx_reply))),] )

ares_parse_txt_reply = _rpythonic_function_(		"ares_parse_txt_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("txt_out",		ctypes.POINTER(ctypes.POINTER(ares_txt_reply))),] )

ares_parse_naptr_reply = _rpythonic_function_(		"ares_parse_naptr_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("naptr_out",		ctypes.POINTER(ctypes.POINTER(ares_naptr_reply))),] )

ares_parse_soa_reply = _rpythonic_function_(		"ares_parse_soa_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("soa_out",		ctypes.POINTER(ctypes.POINTER(ares_soa_reply))),] )

ares_free_string = _rpythonic_function_(		"ares_free_string", ctypes.c_void_p, [("C_str",		ctypes.c_void_p)] )

ares_parse_a_reply = _rpythonic_function_(		"ares_parse_a_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("host",		ctypes.POINTER(ctypes.POINTER(hostent))),
	("addrttls",		ctypes.POINTER(ares_addrttl)),
	("naddrttls",		ctypes.POINTER(ctypes.c_int)),] )

ares_parse_aaaa_reply = _rpythonic_function_(		"ares_parse_aaaa_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("host",		ctypes.POINTER(ctypes.POINTER(hostent))),
	("addrttls",		ctypes.POINTER(ares_addr6ttl)),
	("naddrttls",		ctypes.POINTER(ctypes.c_int)),] )

ares_parse_ptr_reply = _rpythonic_function_(		"ares_parse_ptr_reply", ctypes.c_int, [
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),
	("addr",		ctypes.POINTER(ctypes.c_void_p)),
	("addrlen",		ctypes.c_int),
	("family",		ctypes.c_int),
	("host",		ctypes.POINTER(ctypes.POINTER(hostent))),] )

ares_process = _rpythonic_function_(		"ares_process", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("read_fds",		ctypes.POINTER(fd_set)),
	("write_fds",		ctypes.POINTER(fd_set)),] )

ares_process_fd = _rpythonic_function_(		"ares_process_fd", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("read_fd",		ctypes.c_int),
	("write_fd",		ctypes.c_int),] )

ares_mkquery = _rpythonic_function_(		"ares_mkquery", ctypes.c_int, [
	("name",		ctypes.POINTER(ctypes.c_char)),
	("dnsclass",		ctypes.c_int),
	("C_type",		ctypes.c_int),
	("C_id",		ctypes.c_ushort),
	("rd",		ctypes.c_int),
	("buf",		ctypes.POINTER(ctypes.POINTER(ctypes.c_ubyte))),
	("buflen",		ctypes.POINTER(ctypes.c_int)),] )

ares_set_servers_csv = _rpythonic_function_(		"ares_set_servers_csv", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("servers",		ctypes.POINTER(ctypes.c_char)),] )

ares_get_servers = _rpythonic_function_(		"ares_get_servers", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("servers",		ctypes.POINTER(ctypes.POINTER(ares_addr_node))),] )

ares_free_hostent = _rpythonic_function_(		"ares_free_hostent", ctypes.c_void_p, [
	("host",		ctypes.POINTER(hostent)),] )

ares_free_soa = _rpythonic_function_(		"ares_free_soa", ctypes.c_void_p, [
	("soa",		ctypes.POINTER(ares_soa_reply)),] )

ares_free_data = _rpythonic_function_(		"ares_free_data", ctypes.c_void_p, [("dataptr",		ctypes.c_void_p)] )

ares_strerror = _rpythonic_function_(		"ares_strerror", ctypes.POINTER(ctypes.c_char), [
	("code",		ctypes.c_int),] )

ares_set_servers = _rpythonic_function_(		"ares_set_servers", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("servers",		ctypes.POINTER(ares_addr_node)),] )

ntohl = _rpythonic_function_(		"ntohl", ctypes.c_uint32, [
	("__netlong",		ctypes.c_uint32),] )

ntohs = _rpythonic_function_(		"ntohs", ctypes.c_uint16, [
	("__netshort",		ctypes.c_uint16),] )

htonl = _rpythonic_function_(		"htonl", ctypes.c_uint32, [
	("__hostlong",		ctypes.c_uint32),] )

htons = _rpythonic_function_(		"htons", ctypes.c_uint16, [
	("__hostshort",		ctypes.c_uint16),] )

bindresvport = _rpythonic_function_(		"bindresvport", ctypes.c_int, [
	("__sockfd",		ctypes.c_int),
	("__sock_in",		ctypes.POINTER(sockaddr_in)),] )

bindresvport6 = _rpythonic_function_(		"bindresvport6", ctypes.c_int, [
	("__sockfd",		ctypes.c_int),
	("__sock_in",		ctypes.POINTER(sockaddr_in6)),] )

sendmmsg = _rpythonic_function_(		"sendmmsg", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__vmessages",		ctypes.POINTER(mmsghdr)),
	("__vlen",		ctypes.c_uint),
	("__flags",		ctypes.c_int),] )

socket = _rpythonic_function_(		"socket", ctypes.c_int, [
	("__domain",		ctypes.c_int),
	("__type",		ctypes.c_int),
	("__protocol",		ctypes.c_int),] )

socketpair = _rpythonic_function_(		"socketpair", ctypes.c_int, [
	("__domain",		ctypes.c_int),
	("__type",		ctypes.c_int),
	("__protocol",		ctypes.c_int),
	("__fds",		( ctypes.c_int * 2 )),] )

ares_library_cleanup = _rpythonic_function_(		"ares_library_cleanup", ctypes.c_void_p, [] )

ares_version = _rpythonic_function_(		"ares_version", ctypes.POINTER(ctypes.c_char), [
	("version",		ctypes.POINTER(ctypes.c_int)),] )

ares_init = _rpythonic_function_(		"ares_init", ctypes.c_int, [
	("channelptr",		ctypes.POINTER(ctypes.POINTER(ares_channeldata))),] )

ares_init_options = _rpythonic_function_(		"ares_init_options", ctypes.c_int, [
	("channelptr",		ctypes.POINTER(ctypes.POINTER(ares_channeldata))),
	("options",		ctypes.POINTER(ares_options)),
	("optmask",		ctypes.c_int),] )

ares_save_options = _rpythonic_function_(		"ares_save_options", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("options",		ctypes.POINTER(ares_options)),
	("optmask",		ctypes.POINTER(ctypes.c_int)),] )

gnu_dev_major = _rpythonic_function_(		"gnu_dev_major", ctypes.c_uint, [
	("__dev",		ctypes.c_ulonglong),] )

gnu_dev_minor = _rpythonic_function_(		"gnu_dev_minor", ctypes.c_uint, [
	("__dev",		ctypes.c_ulonglong),] )

gnu_dev_makedev = _rpythonic_function_(		"gnu_dev_makedev", ctypes.c_ulonglong, [
	("__major",		ctypes.c_uint),
	("__minor",		ctypes.c_uint),] )

shutdown = _rpythonic_function_(		"shutdown", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__how",		ctypes.c_int),] )

sockatmark = _rpythonic_function_(		"sockatmark", ctypes.c_int, [
	("__fd",		ctypes.c_int),] )

isfdtype = _rpythonic_function_(		"isfdtype", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__fdtype",		ctypes.c_int),] )

process_vm_readv = _rpythonic_function_(		"process_vm_readv", ctypes.c_int64, [
	("__pid",		ctypes.c_int),
	("__lvec",		ctypes.POINTER(iovec)),
	("__liovcnt",		ctypes.c_uint64),
	("__rvec",		ctypes.POINTER(iovec)),
	("__riovcnt",		ctypes.c_uint64),
	("__flags",		ctypes.c_uint64),] )

process_vm_writev = _rpythonic_function_(		"process_vm_writev", ctypes.c_int64, [
	("__pid",		ctypes.c_int),
	("__lvec",		ctypes.POINTER(iovec)),
	("__liovcnt",		ctypes.c_uint64),
	("__rvec",		ctypes.POINTER(iovec)),
	("__riovcnt",		ctypes.c_uint64),
	("__flags",		ctypes.c_uint64),] )

ares_destroy_options = _rpythonic_function_(		"ares_destroy_options", ctypes.c_void_p, [
	("options",		ctypes.POINTER(ares_options)),] )

ares_dup = _rpythonic_function_(		"ares_dup", ctypes.c_int, [
	("dest",		ctypes.POINTER(ctypes.POINTER(ares_channeldata))),
	("src",		ctypes.POINTER(ares_channeldata)),] )

ares_destroy = _rpythonic_function_(		"ares_destroy", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),] )

ares_cancel = _rpythonic_function_(		"ares_cancel", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),] )

ares_set_local_ip4 = _rpythonic_function_(		"ares_set_local_ip4", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("local_ip",		ctypes.c_uint),] )

ares_set_local_ip6 = _rpythonic_function_(		"ares_set_local_ip6", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("local_ip6",		ctypes.POINTER(ctypes.c_ubyte)),] )

select = _rpythonic_function_(		"select", ctypes.c_int, [
	("__nfds",		ctypes.c_int),
	("__readfds",		ctypes.POINTER(fd_set)),
	("__writefds",		ctypes.POINTER(fd_set)),
	("__exceptfds",		ctypes.POINTER(fd_set)),
	("__timeout",		ctypes.POINTER(timeval)),] )

pselect = _rpythonic_function_(		"pselect", ctypes.c_int, [
	("__nfds",		ctypes.c_int),
	("__readfds",		ctypes.POINTER(fd_set)),
	("__writefds",		ctypes.POINTER(fd_set)),
	("__exceptfds",		ctypes.POINTER(fd_set)),
	("__timeout",		ctypes.POINTER(timespec)),
	("__sigmask",		ctypes.POINTER(__sigset_t)),] )

recvmmsg = _rpythonic_function_(		"recvmmsg", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__vmessages",		ctypes.POINTER(mmsghdr)),
	("__vlen",		ctypes.c_uint),
	("__flags",		ctypes.c_int),
	("__tmo",		ctypes.POINTER(timespec)),] )

recvfrom = _rpythonic_function_(		"recvfrom", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__buf",		ctypes.POINTER(ctypes.c_void_p)),
	("__n",		ctypes.c_uint64),
	("__flags",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__addr_len",		ctypes.POINTER(ctypes.c_uint)),] )

sendmsg = _rpythonic_function_(		"sendmsg", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__message",		ctypes.POINTER(msghdr)),
	("__flags",		ctypes.c_int),] )

recvmsg = _rpythonic_function_(		"recvmsg", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__message",		ctypes.POINTER(msghdr)),
	("__flags",		ctypes.c_int),] )

bind = _rpythonic_function_(		"bind", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__len",		ctypes.c_uint),] )

getsockname = _rpythonic_function_(		"getsockname", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__len",		ctypes.POINTER(ctypes.c_uint)),] )

connect = _rpythonic_function_(		"connect", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__len",		ctypes.c_uint),] )

getpeername = _rpythonic_function_(		"getpeername", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__len",		ctypes.POINTER(ctypes.c_uint)),] )

ares_query = _rpythonic_function_(		"ares_query", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("name",		ctypes.POINTER(ctypes.c_char)),
	("dnsclass",		ctypes.c_int),
	("C_type",		ctypes.c_int),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.POINTER(ctypes.c_ubyte),ctypes.c_int,)),
	("arg",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_search = _rpythonic_function_(		"ares_search", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("name",		ctypes.POINTER(ctypes.c_char)),
	("dnsclass",		ctypes.c_int),
	("C_type",		ctypes.c_int),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.POINTER(ctypes.c_ubyte),ctypes.c_int,)),
	("arg",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_gethostbyname = _rpythonic_function_(		"ares_gethostbyname", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("name",		ctypes.POINTER(ctypes.c_char)),
	("family",		ctypes.c_int),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.POINTER(hostent),)),
	("arg",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_sock_state_cb = _rpythonic_function_(		"ares_sock_state_cb", ctypes.c_void_p, [
	("data",		ctypes.POINTER(ctypes.c_void_p)),
	("socket_fd",		ctypes.c_int),
	("readable",		ctypes.c_int),
	("writable",		ctypes.c_int),] )

ares_gethostbyname_file = _rpythonic_function_(		"ares_gethostbyname_file", ctypes.c_int, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("name",		ctypes.POINTER(ctypes.c_char)),
	("family",		ctypes.c_int),
	("host",		ctypes.POINTER(ctypes.POINTER(hostent))),] )

ares_gethostbyaddr = _rpythonic_function_(		"ares_gethostbyaddr", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("addr",		ctypes.POINTER(ctypes.c_void_p)),
	("addrlen",		ctypes.c_int),
	("family",		ctypes.c_int),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.POINTER(hostent),)),
	("arg",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_getnameinfo = _rpythonic_function_(		"ares_getnameinfo", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("sa",		ctypes.POINTER(sockaddr)),
	("salen",		ctypes.c_uint),
	("flags",		ctypes.c_int),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.POINTER(ctypes.c_char),ctypes.POINTER(ctypes.c_char),)),
	("arg",		ctypes.POINTER(ctypes.c_void_p)),] )

readv = _rpythonic_function_(		"readv", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__iovec",		ctypes.POINTER(iovec)),
	("__count",		ctypes.c_int),] )

writev = _rpythonic_function_(		"writev", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__iovec",		ctypes.POINTER(iovec)),
	("__count",		ctypes.c_int),] )

preadv = _rpythonic_function_(		"preadv", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__iovec",		ctypes.POINTER(iovec)),
	("__count",		ctypes.c_int),
	("__offset",		ctypes.c_int64),] )

pwritev = _rpythonic_function_(		"pwritev", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__iovec",		ctypes.POINTER(iovec)),
	("__count",		ctypes.c_int),
	("__offset",		ctypes.c_int64),] )

ares_nameinfo_callback = _rpythonic_function_(		"ares_nameinfo_callback", ctypes.c_void_p, [
	("arg",		ctypes.POINTER(ctypes.c_void_p)),
	("status",		ctypes.c_int),
	("timeouts",		ctypes.c_int),
	("node",		ctypes.POINTER(ctypes.c_char)),
	("service",		ctypes.POINTER(ctypes.c_char)),] )

ares_sock_create_callback = _rpythonic_function_(		"ares_sock_create_callback", ctypes.c_int, [
	("socket_fd",		ctypes.c_int),
	("C_type",		ctypes.c_int),
	("data",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_library_init = _rpythonic_function_(		"ares_library_init", ctypes.c_int, [
	("flags",		ctypes.c_int),] )

ares_set_local_dev = _rpythonic_function_(		"ares_set_local_dev", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("local_dev_name",		ctypes.POINTER(ctypes.c_char)),] )

ares_set_socket_callback = _rpythonic_function_(		"ares_set_socket_callback", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_int,ctypes.c_int,ctypes.POINTER(ctypes.c_void_p),)),
	("user_data",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_send = _rpythonic_function_(		"ares_send", ctypes.c_void_p, [
	("channel",		ctypes.POINTER(ares_channeldata)),
	("qbuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("qlen",		ctypes.c_int),
	("callback",		ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),ctypes.c_int,ctypes.c_int,ctypes.POINTER(ctypes.c_ubyte),ctypes.c_int,)),
	("arg",		ctypes.POINTER(ctypes.c_void_p)),] )

ares_callback = _rpythonic_function_(		"ares_callback", ctypes.c_void_p, [
	("arg",		ctypes.POINTER(ctypes.c_void_p)),
	("status",		ctypes.c_int),
	("timeouts",		ctypes.c_int),
	("abuf",		ctypes.POINTER(ctypes.c_ubyte)),
	("alen",		ctypes.c_int),] )

ares_host_callback = _rpythonic_function_(		"ares_host_callback", ctypes.c_void_p, [
	("arg",		ctypes.POINTER(ctypes.c_void_p)),
	("status",		ctypes.c_int),
	("timeouts",		ctypes.c_int),
	("hostent",		ctypes.POINTER(hostent)),] )

getsockopt = _rpythonic_function_(		"getsockopt", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__level",		ctypes.c_int),
	("__optname",		ctypes.c_int),
	("__optval",		ctypes.POINTER(ctypes.c_void_p)),
	("__optlen",		ctypes.POINTER(ctypes.c_uint)),] )

setsockopt = _rpythonic_function_(		"setsockopt", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__level",		ctypes.c_int),
	("__optname",		ctypes.c_int),
	("__optval",		ctypes.POINTER(ctypes.c_void_p)),
	("__optlen",		ctypes.c_uint),] )

listen = _rpythonic_function_(		"listen", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__n",		ctypes.c_int),] )

accept = _rpythonic_function_(		"accept", ctypes.c_int, [
	("__fd",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__addr_len",		ctypes.POINTER(ctypes.c_uint)),] )

send = _rpythonic_function_(		"send", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__buf",		ctypes.POINTER(ctypes.c_void_p)),
	("__n",		ctypes.c_uint64),
	("__flags",		ctypes.c_int),] )

recv = _rpythonic_function_(		"recv", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__buf",		ctypes.POINTER(ctypes.c_void_p)),
	("__n",		ctypes.c_uint64),
	("__flags",		ctypes.c_int),] )

sendto = _rpythonic_function_(		"sendto", ctypes.c_int64, [
	("__fd",		ctypes.c_int),
	("__buf",		ctypes.POINTER(ctypes.c_void_p)),
	("__n",		ctypes.c_uint64),
	("__flags",		ctypes.c_int),
	("__addr",		ctypes.POINTER(sockaddr)),
	("__addr_len",		ctypes.c_uint),] )


_rpythonic_convert_structs_to_objects()

_rpythonic_setup_return_wrappers()
_rpythonic_make_nice_global_enums_()
_rpythonic_clean_up_missing_functions_()
_rpythonic_strip_prefixes_(['ares_', 'ARES_'])